### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by blacksonic** [pdezwart/php-amqp#112]
I get 'Segmentation fault' when output the envelopes content via var_dump with PECL version  1.4

**Comment by pinepain** [comment]
@blacksonic do you have this bug with latest (1.6.0 beta2) php-amqp version?

**Comment by lstrojny** [comment]
Ping @blacksonic

**Comment by blacksonic** [comment]
havent checked it, because not used amqp for queue processing

**Comment by pinepain** [comment]
@lstrojny lets' close this issue as it too old and we didn't reproduced it nor getting any feedback for a long time.
