### ISSUE TITLE
Expose the underlying socket of a connection

### ISSUE THREAD

**Issue by joshdifabio** [pdezwart/php-amqp#113]
It would be helpful to be able to access a connection's underlying socket in order to utilise stream_select, socket_select and libevent in order to detect inbound AMQP messages.

An event-driven program (e.g. one implemented using ReactPHP) will generally use *_select or libevent to listen for activity on a number of sockets (e.g. with MySQL and ZeroMQ we can get the underlying socket and register them with libevent or add them to *_select) in order to provide maximum responsiveness and efficiency (i.e. versus sleeping and polling).

I would possibly suggest a getSocket method on the Connection class.

**Comment by pinepain** [comment]
> access a connection's underlying socket ... to detect inbound AMQP messages

That doesn't work strait this way. As AMQP uses connection multiplexing (channels) and as it also has numerous methods different from `basic.get-ok`, `basic.get-empty`, `basic.deliver`  and `basic.return` (methods that holds messages). Also you will have to deal manually with AMQP frames and decode them, so what you'll actually get - [php-amqplib](https://github.com/videlalvaro/php-amqplib) but in slightly pervert way. If you need event-driven interface to AMQP protocol in PHP - use [php-amqplib](https://github.com/videlalvaro/php-amqplib).

I have plans to provide asynchronous interface to AMQP, but have no specific due date for that neither specific requirements for it or so.

**Comment by pinepain** [comment]
From rabbitmq-c docs for [`int amqp_get_sockfd(amqp_connection_state_t state)`](https://github.com/alanxz/rabbitmq-c/blob/937c10bbe64a36579bc8bafcd29554e786143c86/librabbitmq/amqp.h#L1044) function:

>Warning Use the socket returned from this function carefully, incorrect use of the socket outside of the library will lead to undefined behavior. Additionally rabbitmq-c may use the socket differently version-to-version, what may work in one version, may break in the next version. Be sure to throughly test any applications that use the socket returned by this function especially when using a newer version of rabbitmq-c.

So potential risks from exposing socket for selecting are higher then benefit, so I don't think it worth to do this.

**Comment by pinepain** [comment]
@lstrojny I guess we can close this one for reasons written above and as original issue was filled in 2014 and it's 2017 nowaday. We could consider sth like this in a v2 (#257) or if someone (probably, original author @joshdifabio, if he still interested) describe how this exposed socket could be useful (taking in mind written above about how that socket used or may be used withing librabbitmq internals).

**Comment by lstrojny** [comment]
Alright, closing
