### ISSUE TITLE
Misuse of release notes

### ISSUE THREAD

**Issue by pierrejoye** [pdezwart/php-amqp#117]
hi

The releases notes are misused in package.xml

Older releases should be in the changelog > release tags.

If you like to support automatic conversions of the changelog to pickle, it would be nice to fix it. It would be good anyway for the current pecl.php.net so it can be displayed on a per release basis.

**Comment by pinepain** [comment]
@lstrojny this fixed in #181, I guess this issue can be closed.

**Comment by lstrojny** [comment]
No, that is still wrong in the package.xml

**Comment by lstrojny** [comment]
Ignore what I said, saw the PR change later ;)

**Comment by pinepain** [comment]
@lstrojny so everything fine now? Close this one?

**Comment by lstrojny** [comment]
Yep :+1:
