### ISSUE TITLE
AMQPConnectionException with message (unknown error)

### ISSUE THREAD

**Issue by pinguo-shenqiang** [pdezwart/php-amqp#119]
Stack trace:
#0 /home/worker/data/www/CC_Server/protected/modules/mq/models/logic/MqModelLogicEvent.php(131): AMQPQueue->get()
#1 /home/worker/data/www/CC_Server/protected/modules/mq/commands/EventCommand.php(63): MqModelLogicEvent->dispatch('msg-events')
#2 [internal function]: EventCommand->actionDispatch('msg-events')
#3 /home/worker/data/www/phplib/yii-1.1.13/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(EventCommand), Array)
#4 /home/worker/data/www/phplib/yii-1.1.13/console/CConsoleCommandRunner.php(67): CConsoleCommand->run(Array)
#5 /home/worker/data/www/phplib/yii-1.1.13/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
#6 /home/worker/data/www/phplib/yii-1.1.13/base/CApplication.php(169): CConsoleApplication->processRequest()
#7 /home/worker/data/www/phplib/yii-1.1.13/yiic.php(33): CApplication->run()
#8 /home/worker/data/www/CC_Server/protected/yiic.php(31): require_once('/home/worker/da...')
#9 /home/worker/data/www/CC_Server/protected/yiic(4): require_once('/home/worker/da...')

**Comment by lstrojny** [comment]
Closing
