### ISSUE TITLE
packagist.org

### ISSUE THREAD

**Issue by EagleEyeJohn** [pdezwart/php-amqp#120]
https://packagist.org/packages/pdezwart/php-amqp/maintainers/
please could you register with packagist so that you can become the registered maintainer?

And then also add the "GitHub Service Hook

Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Service Hooks". Pick "Packagist" in the list, and add your API token (see above), plus your Packagist username if it is not the same as on GitHub. Check the "Active" box and submit the form."

**Comment by lstrojny** [comment]
@pdezwart sorry for the late response but I didn’t get an invite to an organisation. Could you try again?

**Comment by pdezwart** [comment]
Crap sorry dude. I'll do it tonight!

**Comment by lstrojny** [comment]
Thanks!

**Comment by stof** [comment]
why would you register stubs on Packagist ? Stubs are not working code anyway, so there is no real reason to define a dependency on them with composer

**Comment by pinepain** [comment]
It was kinda experiment. Anyway, I see nothing dramatically wrong to provide stubs to users via packagist,  so they can just `require pdezwart/php-amqp-stubs: *` and have nice code completion for amqp-related stuff. As for now, it is a solution that may work, for vast majority of php-amqp-beginners.
