### ISSUE TITLE
‘amqp_exchange_declare‘ argument error

### ISSUE THREAD

**Issue by wujibing** [pdezwart/php-amqp#135]
/root/amqp-1.4.0/amqp_exchange.c:515:2: error: incompatible type for argument 7 of 'amqp_exchange_declare'
In file included from /usr/local/include/amqp.h:732:0,
                 from /root/amqp-1.4.0/amqp_exchange.c:42:
/usr/local/include/amqp_framing.h:798:11: note: expected 'amqp_boolean_t' but argument is of type 'amqp_table_t'
/root/amqp-1.4.0/amqp_exchange.c:515:2: error: too few arguments to function 'amqp_exchange_declare'

amqp_exchange_declare defined:
AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state,
 amqp_channel_t channel,
 amqp_bytes_t exchange,
 amqp_bytes_t type, 
amqp_boolean_t passive, 
amqp_boolean_t durable, 
amqp_boolean_t auto_delete, 
amqp_boolean_t internal, 
amqp_table_t arguments);

amqp_exchange.c used:
amqp_exchange_declare(
                connection->connection_resource->connection_state,
                channel->channel_id,
                amqp_cstring_bytes(exchange->name),
                amqp_cstring_bytes(exchange->type),
                exchange->passive,
                exchange->durable,
                *arguments
        );

**Comment by lstrojny** [comment]
Closing
