### ISSUE TITLE
RabbitMQ 3.4.3 security update breaks exchange binding

### ISSUE THREAD

**Issue by alextech** [pdezwart/php-amqp#137]
After performing recommended security update from 3.4.2 to 3.4.3, binding to an exchange using $queue->consume($callback, AMQP_AUTOACK); 
where $queue is created from AMQP_EX_TYPE_TOPIC
causes exception with message "Unknown server error occurred."

Tried updating to latest master in librabbitmq-c. It is now at 0.5.3. Compilation was ok but now the queue consumption exits with "Library error: unexpected protocol state".  Attempting to use 0.5.2. causes segmentation fault at extension loading. Tried to use latest master in php-amqp repository with similar results.

In both cases there is a significant delay before exit. Connection is created for a few seconds before consume() function crashes.

Using with php 5.6.4 in cli mode. Unfortunately, I do not know how to get more technical debugging details of a pecl extension.

**Comment by alextech** [comment]
unable to reproduce later in the day. seems to be inconsisent or made a mistake in upgrade path.

**Comment by pinepain** [comment]
To make sure everything is OK try to build both rabbitmq-c and php-amqp from master branches

**Comment by alextech** [comment]
yes, have to be careful to always recompile rabbitmq-c and php-amqp on all rabbitmq updates. Thanks.
