### ISSUE TITLE
Release Schedule 1.6.0

### ISSUE THREAD

**Issue by lstrojny** [pdezwart/php-amqp#140]
@pinepain  Here is my plan for the 1.6.0 release. I just released beta1 and would not add more features now (should have shipped a release earlier already)

 - Week 4: 1.6.0 beta1 release
 - Week 5: 1.6.0 beta2 (replaces beta1, packaging mistake)
 - Week 8: 1.6.0 beta3 (if required)
 - Week 10: 1.6.0 stable release

**Comment by llaville** [comment]
Hi @lstrojny
You've released the 1.6.0beta1 with a stable state. Should it be beta instead ?

BTW, one question, where is gone the 1.5.0 ?

**Comment by lstrojny** [comment]
@llaville that’s definitly a mistake, will pull the release so people are not automatically installing it. There won't be a 1.5.

**Comment by lstrojny** [comment]
Done

**Comment by llaville** [comment]
Thanks

**Comment by lstrojny** [comment]
I would like to resolve #149, then ship a beta3 and be done with it. @pinepain agreed?

**Comment by pinepain** [comment]
I would also suggest to add following issues to 1.6.0 milestone:

 - Redefine channel_max https://github.com/pdezwart/php-amqp/issues/144: I would suggest to move `channel_max`, `frame_max` and `hearbeat` connection settings to userspace (via connection constructor argumenst). This will let use php-amqp extension with custom AMQP broker configuration and also will bring limited heartbeat support (it will work during blocking connections, which in most cases is what users need).
 - Misuse of release notes, https://github.com/pdezwart/php-amqp/issues/117. This one is about reviewing `package.xml` structure and is not too large, but should bring cleaner changes and improvements in http://pecl.php.net/amqp output.

As to existent https://github.com/pdezwart/php-amqp/issues/112 issue: when we'll figure out what is wrong in https://github.com/pdezwart/php-amqp/issues/149, both can be closed, i guess.

**Comment by pinepain** [comment]
I would also propose to add rabbitmq-c version check during php-amqp configuration and simply drop old rabbitmq-c versions support.

**Comment by lstrojny** [comment]
@pinepain fine with incrementing required version to 0.6.0, package.xml is a low hanging fruit but also not terribly important and #144 is for me a nice to have, do you agree?

**Comment by jpastoor** [comment]
Any updated schedule for a stable release?

**Comment by pinepain** [comment]
@lstrojny sorry, I've been busy and totally overcommitted, I will try to finish on #144 and hope we'll make more users happy. Once again, sorry for such delay.

**Comment by lstrojny** [comment]
@pinepain no need to apologize, I am really greatfull for your contributions.

**Comment by pinepain** [comment]
@lstrojny After mergetd https://github.com/pdezwart/php-amqp/pull/164 and https://github.com/pdezwart/php-amqp/pull/166, can we roll new beta and plan release schedule?

**Comment by lstrojny** [comment]
Soudns good!

**Comment by lstrojny** [comment]
Let’s roll another beta, wait two more weeks and go stable if nothing major happens. Agreed?

**Comment by pinepain** [comment]
Yeah, it would be great.

**Comment by pinepain** [comment]
@lstrojny, beta live for 1 month, looks like it is ok or nobody tried it :smile:. Going stable?

**Comment by lstrojny** [comment]
Agreed, let’s ship.

**Comment by lstrojny** [comment]
@pinepain any idea on #170 ?

**Comment by pinepain** [comment]
I'll give it a look.

**Comment by pinepain** [comment]
@lstrojny issue #170 should be fixed by PR #172

**Comment by pinepain** [comment]
@lstrojny can we release 1.6.0 stable from current master (and close all related issues) so that we can merge #181 and then release beta for php7 support (say, name it as 1.7.0)?

**Comment by lstrojny** [comment]
Makes sense

**Comment by lstrojny** [comment]
1.6.0 stable has been released
