### ISSUE TITLE
Error: too few arguments to function 'amqp_exchange_declare'

### ISSUE THREAD

**Issue by GeorgeFarikson** [pdezwart/php-amqp#159]
I try to install amqp-1.6.0beta2 via PECL and see error "Error: too few arguments to function 'amqp_exchange_declare'". Rabbitmq-c cloned from - https://github.com/alanxz/rabbitmq-c.git with tag v0.6.0.

OS: Ubuntu 14.10

**Comment by lstrojny** [comment]
Which version of librabbitmq do you use?

**Comment by pinepain** [comment]
Note, that compiled and linked library .so files may be different, so in most cases you should better remove older `librabbitmq` versions and install fresh one on top.

**Comment by GeorgeFarikson** [comment]
I use version of librabbitmq 0.6.0 cloned from https://github.com/alanxz/rabbitmq-c.
inepain: i tried to remove older librabbitmq and install different versions for compatibility, but each time received an error with compile. The same day I installed it on Debian without problems using the MAKE on compile, but on try install on Ubuntu (use CMAKE compiler) i have some problem with compatibility, maybe create stable package dependencies for install this under Ubuntu OS?

**Comment by pinepain** [comment]
Look how we do it in dev environment in [current `provision.sh`](https://github.com/pdezwart/php-amqp/commit/f3fa5c4203426873dd1e00bc0da589bf77bc7a8b#diff-cc8d2c64d68b464acd2837ece8e20711R71) script (see the rabbitmq-c related part).

As to Ubuntu packages, `librabbitmq` is often quite outdated there (even [in Vivid it is 0.5.2](http://packages.ubuntu.com/source/vivid/librabbitmq)), so relying on it may not be always a proper solution.

**Comment by stof** [comment]
@pinepain I'm getting the same error with librabbitmq 0.6.0 (and I removed the apt package first so I don't have any other version)

**Comment by stof** [comment]
@pinepain I suspect it is because https://github.com/pdezwart/php-amqp/pull/153 was merged only after the beta2 release. any chance to release a beta3 on pecl ?

**Comment by pinepain** [comment]
@stof, @GeorgeFarikson  I'm terribly sorry. For some reason I was sure beta3 already released, but then I remember that we have in-progress issues that we planed to close and merge before beta3 release. 


@lstrojny can you release current master as 1.6.0beta3?

As to [issue #144 Redefine channel_max](https://github.com/pdezwart/php-amqp/issues/144), it is in progress, but I'm a bit overcommited now, so no specific ETA for now, I hope I will done it in this month. 

As to [issue #158 Add ability to re-attach consuming callback](https://github.com/pdezwart/php-amqp/pull/158), if we agree with `AMQPQueue::getConsumerTag()` method return value it can be and probably should be goes to 1.6.0 too.

**Comment by GeorgeFarikson** [comment]
@pinepain so I hope you find time to close your issues, but now i got successfully install
```librabbitmq 0.5.2```
from here http://archive.ubuntu.com/ubuntu/pool/universe/libr/librabbitmq/librabbitmq_0.5.2.orig.tar.gz use manual compile but also had to install the ```apt-get install pkg-config```.
Then I installed amqp-1.4.0 ```pecl install amqp-1.4.0```

I'ts worked! Please let me know how to solve your issues! Thank you!

**Comment by lstrojny** [comment]
1.6.0 beta3 has been released

**Comment by GeorgeFarikson** [comment]
Thank you for your help! *beta3 already to install and working I'm check it and close this issue
