### ISSUE TITLE
"make test" failure when I complete the "make". 

### ISSUE THREAD

**Issue by bsll** [pdezwart/php-amqp#160]
I use the php-5.6.0 ,and amqp-1.4.0, rabbitmq-c-0.5.2 .

I can finish the process,but when I run the "make test",I can't get the all passed results.

Like this:

PHP         : /usr/local/php56/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 5.6.0
ZEND_VERSION: 2.6.0
PHP_OS      : Linux - Linux hp1 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
INI actual  : /home/cikuu/wxh/rabbitmq/amqp-1.4.0/tmp-php.ini
More .INIs  :  
CWD         : /home/cikuu/wxh/rabbitmq/amqp-1.4.0
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2015-04-15 09:37:24
=====================================================================
FAIL AMQPChannel constructor [tests/amqpchannel_construct_basic.phpt] 
FAIL Multiple AMQPChannels per AMQPConnection [tests/amqpchannel_multi_channel_connection.phpt] 
FAIL AMQPChannel var_dump [tests/amqpchannel_var_dump.phpt] 
FAIL AMQPConnection constructor [tests/amqpconnection_construct_basic.phpt] 
PASS AMQPConnection constructor with amqp.read_timeout ini value set [tests/amqpconnection_construct_ini_read_timeout.phpt] 
PASS AMQPConnection constructor with amqp.timeout ini value set [tests/amqpconnection_construct_ini_timeout.phpt] 
PASS AMQPConnection constructor with both amqp.timeout and amqp.read_timeout ini values set [tests/amqpconnection_construct_ini_timeout_and_read_timeout.phpt] 
PASS AMQPConnection constructor with timeout parameter in creadentials [tests/amqpconnection_construct_with_timeout.phpt] 
PASS AMQPConnection constructor with both timeout and read_timeout parameters in creadentials [tests/amqpconnection_construct_with_timeout_and_read_timeout.phpt] 
PASS AMQPConnection constructor with write_timeout parameter in creadentials [tests/amqpconnection_construct_with_write_timeout.phpt] 
FAIL AMQPConnection persistent connections [tests/amqpconnection_persistent.phpt] 
PASS AMQPConnection constructor [tests/amqpconnection_setPort_int.phpt] 
PASS AMQPConnection setPort with int out of range [tests/amqpconnection_setPort_out_of_range.phpt] 
PASS AMQPConnection setPort with string [tests/amqpconnection_setPort_string.phpt] 
PASS AMQPConnection setReadTimeout float [tests/amqpconnection_setReadTimeout_float.phpt] 
PASS AMQPConnection setReadTimeout int [tests/amqpconnection_setReadTimeout_int.phpt] 
PASS AMQPConnection setReadTimeout out of range [tests/amqpconnection_setReadTimeout_out_of_range.phpt] 
PASS AMQPConnection setReadTimeout string [tests/amqpconnection_setReadTimeout_string.phpt] 
PASS AMQPConnection setTimeout deprecated [tests/amqpconnection_setTimeout_deprecated.phpt] 
PASS AMQPConnection setTimeout float [tests/amqpconnection_setTimeout_float.phpt] 
PASS AMQPConnection setTimeout int [tests/amqpconnection_setTimeout_int.phpt] 
PASS AMQPConnection setTimeout out of range [tests/amqpconnection_setTimeout_out_of_range.phpt] 
PASS AMQPConnection setTimeout string [tests/amqpconnection_setTimeout_string.phpt] 
PASS AMQPConnection setWriteTimeout float [tests/amqpconnection_setWriteTimeout_float.phpt] 
PASS AMQPConnection setWriteTimeout int [tests/amqpconnection_setWriteTimeout_int.phpt] 
PASS AMQPConnection setWriteTimeout out of range [tests/amqpconnection_setWriteTimeout_out_of_range.phpt] 
PASS AMQPConnection setWriteTimeout string [tests/amqpconnection_setWriteTimeout_string.phpt] 
FAIL AMQPConnection too many channels on a connection [tests/amqpconnection_toomanychannels.phpt] 
FAIL AMQPConnection var_dump [tests/amqpconnection_var_dump.phpt] 
FAIL AMQPEnvelope test get*() accessors [tests/amqpenvelope_get_accessors.phpt] 
FAIL AMQPEnvelope var_dump [tests/amqpenvelope_var_dump.phpt] 
FAIL AMQPExchange channel refcount [tests/amqpexchange_channel_refcount.phpt] 
FAIL AMQPExchange constructor [tests/amqpexchange_construct_basic.phpt] 
FAIL AMQPExchange [tests/amqpexchange_declare_basic.phpt] 
FAIL AMQPExchange [tests/amqpexchange_invalid_type.phpt] 
FAIL AMQPExchange [tests/amqpexchange_publish_basic.phpt] 
FAIL AMQPExchange publish with empty routing key [tests/amqpexchange_publish_empty_routing_key.phpt] 
FAIL AMQPExchange set flag string [tests/amqpexchange_set_flag.phpt] 
FAIL AMQPExchange var_dump [tests/amqpexchange_var_dump.phpt] 
FAIL AMQPQueue [tests/amqpqueue_bind_basic.phpt] 
FAIL AMQPQueue [tests/amqpqueue_bind_basic_empty_routing_key.phpt] 
FAIL AMQPQueue [tests/amqpqueue_bind_basic_headers_arguments.phpt] 
FAIL AMQPQueue cancel [tests/amqpqueue_cancel.phpt] 
FAIL AMQPQueue constructor [tests/amqpqueue_construct_basic.phpt] 
FAIL AMQPQueue::consume basic [tests/amqpqueue_consume_basic.phpt] 
FAIL AMQPQueue::consume with timeout [tests/amqpqueue_consume_timeout.phpt] 
FAIL AMQPQueue [tests/amqpqueue_declare_basic.phpt] 
FAIL AMQPQueue declared with empty name [tests/amqpqueue_empty_name.phpt] 
FAIL AMQPQueue::get basic [tests/amqpqueue_get_basic.phpt] 
FAIL AMQPQueue::get empty body [tests/amqpqueue_get_empty_body.phpt] 
FAIL AMQPQueue::get headers [tests/amqpqueue_get_headers.phpt] 
FAIL AMQPQueue::nack [tests/amqpqueue_nack.phpt] 
FAIL AMQPQueue::get headers [tests/amqpqueue_nested_arrays.phpt] 
FAIL AMQPQueue::get headers [tests/amqpqueue_nested_headers.phpt] 
PASS AMQPQueue [tests/amqpqueue_purge_basic.phpt] 
FAIL AMQPQueue [tests/amqpqueue_unbind_basic_empty_routing_key.phpt] 
FAIL AMQPQueue [tests/amqpqueue_unbind_basic_headers_arguments.phpt] 
FAIL AMQPQueue var_dump [tests/amqpqueue_var_dump.phpt] 
FAIL Segfault when publishing to non existent exchange [tests/bug_17831.phpt] 
FAIL AMQPQueue::get() doesn't return the message [tests/bug_19707.phpt] 
PASS Connection Exception [tests/bug_19840.phpt] 
FAIL Constructing AMQPQueue with AMQPConnection segfaults [tests/bug_61533.phpt] 
PASS Constructing AMQPQueue with AMQPConnection segfaults [tests/bug_62354.phpt] 
FAIL Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (1) [tests/bug_gh50-1.phpt] 
FAIL Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (2) [tests/bug_gh50-2.phpt] 
FAIL Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (3) [tests/bug_gh50-3.phpt] 
FAIL Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (4) [tests/bug_gh50-4.phpt] 
FAIL Upgrade to RabbitMQ 3.1.0-1: AMQPConnectionException: connection closed unexpectedly (2) [tests/bug_gh53-2.phpt] 
FAIL Upgrade to RabbitMQ 3.1.0-1: AMQPConnectionException: connection closed unexpectedly [tests/bug_gh53.phpt] 
FAIL Compare version in package.xml and module [tests/package-version.phpt] 
=====================================================================
TIME END 2015-04-15 09:37:27

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   44
---------------------------------------------------------------------

Number of tests :   70                70
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   45 ( 64.3%) ( 64.3%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   25 ( 35.7%) ( 35.7%)
---------------------------------------------------------------------
Time taken      :    3 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
AMQPChannel constructor [tests/amqpchannel_construct_basic.phpt]
Multiple AMQPChannels per AMQPConnection [tests/amqpchannel_multi_channel_connection.phpt]
AMQPChannel var_dump [tests/amqpchannel_var_dump.phpt]
AMQPConnection constructor [tests/amqpconnection_construct_basic.phpt]
AMQPConnection persistent connections [tests/amqpconnection_persistent.phpt]
AMQPConnection too many channels on a connection [tests/amqpconnection_toomanychannels.phpt]
AMQPConnection var_dump [tests/amqpconnection_var_dump.phpt]
AMQPEnvelope test get*() accessors [tests/amqpenvelope_get_accessors.phpt]
AMQPEnvelope var_dump [tests/amqpenvelope_var_dump.phpt]
AMQPExchange channel refcount [tests/amqpexchange_channel_refcount.phpt]
AMQPExchange constructor [tests/amqpexchange_construct_basic.phpt]
AMQPExchange [tests/amqpexchange_declare_basic.phpt]
AMQPExchange [tests/amqpexchange_invalid_type.phpt]
AMQPExchange [tests/amqpexchange_publish_basic.phpt]
AMQPExchange publish with empty routing key [tests/amqpexchange_publish_empty_routing_key.phpt]
AMQPExchange set flag string [tests/amqpexchange_set_flag.phpt]
AMQPExchange var_dump [tests/amqpexchange_var_dump.phpt]
AMQPQueue [tests/amqpqueue_bind_basic.phpt]
AMQPQueue [tests/amqpqueue_bind_basic_empty_routing_key.phpt]
AMQPQueue [tests/amqpqueue_bind_basic_headers_arguments.phpt]
AMQPQueue cancel [tests/amqpqueue_cancel.phpt]
AMQPQueue constructor [tests/amqpqueue_construct_basic.phpt]
AMQPQueue::consume basic [tests/amqpqueue_consume_basic.phpt]
AMQPQueue::consume with timeout [tests/amqpqueue_consume_timeout.phpt]
AMQPQueue [tests/amqpqueue_declare_basic.phpt]
AMQPQueue declared with empty name [tests/amqpqueue_empty_name.phpt]
AMQPQueue::get basic [tests/amqpqueue_get_basic.phpt]
AMQPQueue::get empty body [tests/amqpqueue_get_empty_body.phpt]
AMQPQueue::get headers [tests/amqpqueue_get_headers.phpt]
AMQPQueue::nack [tests/amqpqueue_nack.phpt]
AMQPQueue::get headers [tests/amqpqueue_nested_arrays.phpt]
AMQPQueue::get headers [tests/amqpqueue_nested_headers.phpt]
AMQPQueue [tests/amqpqueue_unbind_basic_empty_routing_key.phpt]
AMQPQueue [tests/amqpqueue_unbind_basic_headers_arguments.phpt]
AMQPQueue var_dump [tests/amqpqueue_var_dump.phpt]
Segfault when publishing to non existent exchange [tests/bug_17831.phpt]
AMQPQueue::get() doesn't return the message [tests/bug_19707.phpt]
Constructing AMQPQueue with AMQPConnection segfaults [tests/bug_61533.phpt]
Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (1) [tests/bug_gh50-1.phpt]
Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (2) [tests/bug_gh50-2.phpt]
Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (3) [tests/bug_gh50-3.phpt]
Channel creation race condition (https://github.com/pdezwart/php-amqp/issues/50) (4) [tests/bug_gh50-4.phpt]
Upgrade to RabbitMQ 3.1.0-1: AMQPConnectionException: connection closed unexpectedly (2) [tests/bug_gh53-2.phpt]
Upgrade to RabbitMQ 3.1.0-1: AMQPConnectionException: connection closed unexpectedly [tests/bug_gh53.phpt]
Compare version in package.xml and module [tests/package-version.phpt]

**Comment by pinepain** [comment]
Please, post also [`test-report.sh`](https://github.com/pdezwart/php-amqp/blob/master/test-report.sh) command output and specify RabbitMQ version you use.

**Comment by bsll** [comment]
I don't know about the test-report.sh.
the process is like this:
tar zxvf amqp-1.4.0.tgz && cd amqp-1.4.0
/usr/local/php56/bin/phpize

Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226

./configure --with-php-config=/usr/local/php56/bin/php-config --with-amqp --with-librabbitmq-dir=/usr/local/librabbitmq/

checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php56
checking for PHP includes... -I/usr/local/php56/include/php -I/usr/local/php56/include/php/main -I/usr/local/php56/include/php/TSRM -I/usr/local/php56/include/php/Zend -I/usr/local/php56/include/php/ext -I/usr/local/php56/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php56/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/php56/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking for amqp support... yes, shared
checking for amqp... yes, shared
yes
checking for amqp files in default path... found in /usr/local/librabbitmq/
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1966080
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h

make 

I get this:
Libraries have been installed in:
   /home/cikuu/wangxiaohui/rabbitmq/amqp-1.4.0/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

so I run the "make test" , and get many fail...

**Comment by pinepain** [comment]
[`test-report.sh`](https://github.com/pdezwart/php-amqp/blob/master/test-report.sh) is just a shell script that show failed tests diffs and other details. It doesn't packaged into pecl tar.gz, but you can get it from repository any time. It doesn't have any external dependencies (and works with any php extension).

Please, post also against what RabbitMQ version do you run tests. It is important. Normally, you can check that by typing `# sudo rabbitmqctl status`.

**Comment by bsll** [comment]
I'm so sorry for the delay reply. I have solved the problem.I find that it can work even if the 'make test' has many failures.  Anyway,,thanks..
