### ISSUE TITLE
segfault in PHP-FPM with 1.6.0-beta3

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#161]
I installed the 1.6.0beta3 release (with librabbitmq 0.5.2) and this triggers a segfault in PHP-FPM (the cli seems to work fine):

```
php5-fpm crashed with SIGSEGV in zim_amqp_exchange_class_publish()

Cannot access memory at address 0x0
```

I'm using ``PHP 5.6.7-1+deb.sury.org~trusty+1``, with Xdebug 2.2.5

**Comment by pinepain** [comment]
Can you provide the php code that fails? Or does extension itself cause segfault?

**Comment by stof** [comment]
the extension crashes when starting the PHP-FPM service

**Comment by pinepain** [comment]
Hi, I tried to reproduce your issue within our Vagrant dev environment without any luck. Can you try to reproduce the issue within codebase from my branch (https://github.com/pinepain/php-amqp/tree/direct_reply_to) where provisioning get fixed?

**Comment by pinepain** [comment]
@lstrojny propose to close as "can't reproduce".
