### ISSUE TITLE
Please document the supported keys for array arguments

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#162]
Many methods accept an array of settings as argument. Please document the supported keys in these arrays

**Comment by pinepain** [comment]
The syntax and semantics of that arguments depends on the AMQP broker implementation. So if you use RabbitMQ, you should refer to its docs, if you are fan of ActiveMQ, then you go with its docs.

**Comment by pinepain** [comment]
@lstrojny propose to close as issue not related to extension itself.
