### ISSUE TITLE
Outdated Docs on php.net/amqp

### ISSUE THREAD

**Issue by bkw** [pdezwart/php-amqp#17]
The documentation on php.net is out of date and misleading at times. How does the process of updating it work? Anything we can do to help?

**Comment by cboden** [comment]
+1 on having English documentation

**Comment by pinepain** [comment]
Docs was removed from php.net website while they are out of sync and pretty outdated. For now, stubs are the only reliable documentation (as well as tests). I really sorry that we don't have any docs.

I hope we'll get good docs and examples for next major release.
