### ISSUE TITLE
getDeliveryMode always return 0

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#170]
This makes the method unusable, as 0 is not a valid delivery mode.

See https://github.com/swarrot/swarrot/issues/103 for the place where the issue was found

**Comment by pinepain** [comment]
I'll give it a look. Which php, php-amqp, rabbitmq-c and RabbitMQ version do you use?

**Comment by pinepain** [comment]
Please, take a look at [amqpexchange_publish_with_properties.phpt#L125](https://github.com/pdezwart/php-amqp/blob/222c90f27100777fcf3388c5e9cb30998137961c/tests/amqpexchange_publish_with_properties.phpt#L126) test case whether `AMQPEnvelope::getDeliveryMode()` returns `1`.

Can you provide reproducible example for cases when `AMQPEnvelope::getDeliveryMode()` should return `1` but returns `0` instead?

**Comment by pinepain** [comment]
Confirmed. `delivery mode` property should be 1 for nonpersistent and 2 for persistent messages.

**Comment by pinepain** [comment]
@stof Sorry for delay. Can you join us on discussing PR #172 that attempts to fix this issue?

**Comment by lstrojny** [comment]
1.6.0 stable has been released
