### ISSUE TITLE
Tag a new release version and publish it over pecl

### ISSUE THREAD

**Issue by c-datculescu** [pdezwart/php-amqp#175]
Hello.

The heartbeat is implemented in the master version of the extension, but is not published under 1.6beta3. We had to build our own package containing librabbitmq-c 0.7.1 and php-amqp extension in order to be able to use it. This is not so ideal.

Is there any reason for which the latest master is not tagged as beta yet?

Best,
Cristian.

**Comment by lstrojny** [comment]
1.6.0 stable has been released
