### ISSUE TITLE
make problem with ubuntu 14.04

### ISSUE THREAD

**Issue by mikelynn2** [pdezwart/php-amqp#187]
this is when manually downloading and compiling.  does same error with pecl install

root@ip-10-3-75-194:~/amqp-1.6.1# make
/bin/bash /root/amqp-1.6.1/libtool --mode=compile cc  -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/amqp-1.6.1/amqp.c -o amqp.lo 
libtool: compile:  cc -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/amqp-1.6.1/amqp.c  -fPIC -DPIC -o .libs/amqp.o
/bin/bash /root/amqp-1.6.1/libtool --mode=compile cc  -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/amqp-1.6.1/amqp_exchange.c -o amqp_exchange.lo 
libtool: compile:  cc -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/amqp-1.6.1/amqp_exchange.c  -fPIC -DPIC -o .libs/amqp_exchange.o
/bin/bash /root/amqp-1.6.1/libtool --mode=compile cc  -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/amqp-1.6.1/amqp_queue.c -o amqp_queue.lo 
libtool: compile:  cc -I. -I/root/amqp-1.6.1 -DPHP_ATOM_INC -I/root/amqp-1.6.1/include -I/root/amqp-1.6.1/main -I/root/amqp-1.6.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/amqp-1.6.1/amqp_queue.c  -fPIC -DPIC -o .libs/amqp_queue.o
In file included from /root/amqp-1.6.1/amqp_queue.c:51:0:
/root/amqp-1.6.1/amqp_queue.c: In function 'convert_amqp_envelope_to_zval':
/root/amqp-1.6.1/amqp_queue.c:299:51: error: 'AMQP_DELIVERY_NONPERSISTENT' undeclared (first use in this function)
   AMQP_SET_LONG_PROPERTY(envelope->delivery_mode, AMQP_DELIVERY_NONPERSISTENT);
                                                   ^
/root/amqp-1.6.1/php_amqp.h:253:14: note: in definition of macro 'AMQP_SET_LONG_PROPERTY'
  (object) = (value);
              ^
/root/amqp-1.6.1/amqp_queue.c:299:51: note: each undeclared identifier is reported only once for each function it appears in
   AMQP_SET_LONG_PROPERTY(envelope->delivery_mode, AMQP_DELIVERY_NONPERSISTENT);
                                                   ^
/root/amqp-1.6.1/php_amqp.h:253:14: note: in definition of macro 'AMQP_SET_LONG_PROPERTY'
  (object) = (value);
              ^
make: *** [amqp_queue.lo] Error 1

**Comment by pinepain** [comment]
What librabbitmq version do you have?

**Comment by mikelynn2** [comment]
Package: librabbitmq1
Priority: optional
Section: libs
Installed-Size: 112
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Michael Fladischer <FladischerMichael@fladi.at>
Architecture: amd64
Source: librabbitmq
Version: 0.4.1-1
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.0)
Pre-Depends: multiarch-support
Filename: pool/main/libr/librabbitmq/librabbitmq1_0.4.1-1_amd64.deb
Size: 35170
MD5sum: 59f733e1342ff743039cec1d6305fc2c
SHA1: b3af8914e1a09d3f6bbca75bbc7cb9d4b6f94cbc
SHA256: a22a6fa7b3793c441093b25f64d0feb9a33be138856f33815e335ab80a9b5cf7
Description-en: AMQP client library written in C
 RabbitMQ provides robust messaging for applications. It is easy to use, fit
 for purpose at cloud scale and supported on all major operating systems and
 developer platforms. librabbitmq is a C-language AMQP client library for use
 with AMQP servers such as RabbitMQ speaking protocol versions 0-9-1.
 .
 This package includes the library itself.
Description-md5: d813b0dbcf2f33c93fba8ae5959a1228
Homepage: https://github.com/alanxz/rabbitmq-c
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y


********

Package: librabbitmq-dev
Priority: optional
Section: libdevel
Installed-Size: 161
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Michael Fladischer <FladischerMichael@fladi.at>
Architecture: amd64
Source: librabbitmq
Version: 0.4.1-1
Depends: librabbitmq1 (= 0.4.1-1)
Filename: pool/main/libr/librabbitmq/librabbitmq-dev_0.4.1-1_amd64.deb
Size: 26864
MD5sum: 68bf9037042627f63ed556bcd803b7c8
SHA1: 3f69bad7bb5e4bda26ad97e961e81e5942542b5a
SHA256: 413530a3b85b83bf4b9e53d758c6c9d843a47b5a20d45c8e753c92fdf04a9168
Description-en: AMQP client library written in C - Dev Files
 RabbitMQ provides robust messaging for applications. It is easy to use, fit
 for purpose at cloud scale and supported on all major operating systems and
 developer platforms. librabbitmq is a C-language AMQP client library for use
 with AMQP servers such as RabbitMQ speaking protocol versions 0-9-1.
 .
 This package provides the files needed for development.
Description-md5: 328f6d1c1ad91f4390a538abfb93a5cf
Homepage: https://github.com/alanxz/rabbitmq-c
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m

**Comment by pinepain** [comment]
0.4.1 is too outdated, see [requirements](https://github.com/pdezwart/php-amqp#requirements):
> since php-amqp>=1.6.0 librabbitmq >= 0.5.2 required, >= 0.6.0 recommended

**Comment by mikelynn2** [comment]
thanks
