### ISSUE TITLE
Segfault in AMQPQueue::setArguments

### ISSUE THREAD

**Issue by atm08e** [pdezwart/php-amqp#190]
When you call setArguements twice it will cause a segfault in Version 1.6.1/0.7.1. Running the same test case in 1.4.0/0.4.1 exits normally. Perhaps I am using AMQP incorrectly. Please advise.

Backtrace that points to amqp_queue.c:528 being the issue.
[gdb-backtrace.txt](https://github.com/pdezwart/php-amqp/files/64243/gdb-backtrace.txt)

Simple test case that throws the segfault
```php
<?php

$host = 'localhost';
$port = 5672;
$vhost = '/';
$user ='guest';
$password = 'guest';

$tubeToCreate = ['CREATE_UPDATE', 'EMAIL'];
$exchangeName = 'ADAM2';

$rabbit = new AMQPConnection(['heartbeat' => 30]);
$rabbit->setHost($host);
$rabbit->setPort($port);
$rabbit->setVhost($vhost);
$rabbit->setLogin($user);
$rabbit->setPassword($password);
$rabbit->connect();;

$channel = new AMQPChannel($rabbit);
$ex = new AMQPExchange($channel);
$ex->setName($exchangeName);

foreach ($tubeToCreate as $one){
    $channel->setPrefetchCount(1);
    $queue = new AMQPQueue($channel); 
    $qname = 'DELAY_Q_FOR_ROUTE'.$one;
    
    $arguments = [
    "x-dead-letter-exchange" => $exchangeName,
    "x-dead-letter-routing-key" => $one,
    ];
    
    $queue->setName($qname);
    $queue->setFlags(AMQP_DURABLE);
    $queue->setArguments($arguments);
    $queue->declare();
}
```

Version Info for when it throws a Segfault
➜  amqp  php --ri amqp
amqp
Version => 1.6.1
Revision => release
Compiled => Dec  9 2015 @ 15:49:40
AMQP protocol version => 0-9-1
librabbitmq version => 0.7.1
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0

php --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Version Info for normal exit
php --ri amqp

amqp

Version => 1.4.0
Revision => $Revision: 327551 $
Compiled => Dec  2 2015 @ 18:32:37
AMQP protocol version => 0-9-1
librabbitmq version => 0.4.1

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3

php --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.6.1, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Thank you for your efforts.

**Comment by pinepain** [comment]
Can you please try php-amqp 1.7.0? We have fixed and improved a lot there (and added PHP 7 support), BC provided.

P.S.:    `AMQPQueue::declare()` and `AMQPExchange::declare()` are deprecated, use `AMQPQueue::declareQueue()` and `AMQPExchange::declareExchange()` (this is due to `declare` is reserved php construct.

**Comment by atm08e** [comment]
No longer seg faulting in 
Version => 1.7.0alpha1
Revision => release
Compiled => Dec 17 2015 @ 10:17:03
AMQP protocol version => 0-9-1
librabbitmq version => 0.7.1
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

although we are having consumer timeouts now.

Any idea when 1.7.0 will be released?

**Comment by pinepain** [comment]
Can you clarify about consumer timeouts problem? What default timeouts do you have? Normally they all set to 0 (which means no timeouts).

I guess 1.7.0  will be released in a few weeks or so, but you can use it as is even now.

//cc @lstrojny  (in part about release date)

**Comment by c-datculescu** [comment]
Hello. Having the same error happening here. 

We are still tracking down the issue. For now we cannot use the stable 1.6 because of this issue, waiting for 1.7 stable.

**Comment by pinepain** [comment]
@c-datculescu, can you please try my branch from https://github.com/pdezwart/php-amqp/pull/194?

**Comment by c-datculescu** [comment]
Hi. I will try it as soon as i have a little time (presumably over the weekend) and come back with results.

**Comment by c-datculescu** [comment]
@pinepain I managed to test a little bit the branch, looks like it works fine for some of the tests that were failing for us. I will update when i have more details or when i will finish all the tests.

**Comment by pinepain** [comment]
@lstrojny I guess this can be closed as fixed in latest versions.

**Comment by lstrojny** [comment]
Thanks, closed!

**Comment by ArtemGordinsky** [comment]
For anyone who is, like me, hesitant to use an alpha version in production and can't wait for 1.7 to become stable:
Replacing ```AMQPQueue::setArguments()``` with multiple calls to ```AMQPQueue::setArgument()``` seems to work fine.
