### ISSUE TITLE
Windows DDL library for PHP7 version

### ISSUE THREAD

**Issue by scaytrase** [pdezwart/php-amqp#191]
Please, could you build it for us and put it to PECL? 

Current [snaps dir](http://windows.php.net/downloads/pecl/snaps/amqp/) has only beta build with no actual artifacts, only failed logs

**Comment by pinepain** [comment]
I cleaned up windows build config a bit in https://github.com/pinepain/php-amqp/commit/5879bc32826d3a2696cc9a61af676dc185f935d7, but I can't test it anywhere and prove that there are no any other windows-specific errors. Hope we'll roll out a new pecl release after PR https://github.com/pdezwart/php-amqp/pull/194 merged and everything will be fine.

TL;DR

In this issue more general issue revealed: testing on windows platform.

There is [AppVeyor](http://www.appveyor.com/) which looks like a travis but for windows, here is some [phalcon/zephir/appveyour.yml](https://github.com/phalcon/zephir/blob/master/appveyor.yml) and [owl-framework/owl/appeyor.yml](https://github.com/owl-framework/owl/blob/master/appveyor.yml) scenarios which show the way they build and test their extension and may be used as a reference. I guess we may add it support some time, but no estimates right now, though, PR are welcomed, as always. 

Meanwhile I can suggest to use virtualization  for development on windows, I have positive experience with Vagrant over VirtualBox for windows team members, but you may choose what you fits your  (Docker, etc.). This is definitely a workaround in terms of providing binary for windows, so I don't position it as a proper solution. Though, it works and has a lot of benefits, in context of developing on windows, sure, unless production environment is windows, not linux.

**Comment by macintoshplus** [comment]
Please can you tag a new version?
The master build on windows !

**Comment by pinepain** [comment]
Awesome! Thanks for the feedback!

**Comment by lstrojny** [comment]
1.7.0 was released

**Comment by pinepain** [comment]
@lstrojny snaps dir still empty - http://windows.php.net/downloads/pecl/snaps/amqp/. Will it populated later, if ever?

**Comment by scaytrase** [comment]
release empty too
