### ISSUE TITLE
[PHP7] [1.7.0alpha] Consumer timeout exceed

### ISSUE THREAD

**Issue by HarryBird** [pdezwart/php-amqp#192]
hi ~

  I work on php7 and php-amqp-1.7.0 alpha for some test case.

```
✗> php --re amqp | grep -i version
Extension [ <persistent> extension #38 amqp version v1.7.0alpha1-master-dev ] 
```

  my amqp ini config like:
```
 ➜  docker@/data/tianhai/src/rabbitmq-tutorials/php-amqp git:(master) ✗> php -i | grep amqp
Additional .ini files parsed => /usr/local/etc/php7/php.d/amqp.ini,
amqp
amqp.auto_ack => 0 => 0
amqp.channel_max => 256 => 256
amqp.connect_timeout => 0 => 0
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.host => localhost => localhost
amqp.login => guest => guest
amqp.password => guest => guest
amqp.port => 5672 => 5672
amqp.prefetch_count => 3 => 3
amqp.read_timeout => 10 => 10
amqp.timeout => no value => no value
amqp.vhost => / => /
amqp.write_timeout => 0 => 0
```

  when I try to consume the queue , I got a AMQPQueueException like
```
 [*] Waiting for logs. To exit press CTRL+C
AMQPQueueException Object
(
    [message:protected] => Consumer timeout exceed
    [string:Exception:private] =>
    [code:protected] => 0
    [file:protected] => /data/tianhai/src/rabbitmq-tutorials/php-amqp/receive_logs.php
    [line:protected] => 41
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /data/tianhai/src/rabbitmq-tutorials/php-amqp/receive_logs.php
                    [line] => 41
                    [function] => consume
                    [class] => AMQPQueue
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Closure Object
                                (
                                    [static] => Array
                                        (
                                            [max_jobs] =>
                                        )

                                    [parameter] => Array
                                        (
                                            [$message] => <required>
                                            [$q] => <required>
                                        )

                                )
```

  I have a old workspace on php5 & amqp 1.4.0,  run same script and success~
  I think something change in 1.7.0alpha1, would you please follow it~

Thanks~

**Comment by sshilko** [comment]
```
	connection_params.read_timeout = (int) PHP_AMQP_READ_THIS_PROP_DOUBLE("read_timeout");
	connection_params.write_timeout = (int) PHP_AMQP_READ_THIS_PROP_DOUBLE("write_timeout");
	connection_params.connect_timeout = (int) PHP_AMQP_READ_THIS_PROP_DOUBLE("connect_timeout");
```

Are those seconds or milliseconds? ( i get alot of "Library error: connection closed unexpectedly" and "Library error: a socket error occurred" when setting values to 2 or 3

**Comment by pinepain** [comment]
@sshilko those are in seconds, but you can specify timeouts as float (btw, it's a bug that there are int casting) to specify msec part, so something like `2.5` will be real 2 and a half seconds. I'll fix this bug with int casting asap.

**Comment by sshilko** [comment]
@pinepain thx, ill switch to connect instead of pconnect and will get more debug info and create separate ticket.. i had impression it was milliseconds and thats why "timeout" and "socket closed" appeared.

but there is (for me) something fishy going on around pconnect in 1.7.0alpha+php-fpm5.6+librabbitmq0.7.1 (will open separate issue later on)

**Comment by pinepain** [comment]
@HarryBird, you have `amqp.read_timeout => 10` so it means that if there are no any incoming data for 10 seconds on connection, exception will be thrown (but you should be able to use channel and underlying connection), so basically if you want to wait for messages forever, just set it to `0`.

**Comment by HarryBird** [comment]
it's nothing about `amqp.read_timeout` on my workspace.

Any value assign to `amqp.read_timeout`,  I got exception with message "Consumer timeout exceed"  immediately.

**Comment by pinepain** [comment]
@sshilko, read timeout is set on [amqp_connection_resource.c:179](https://github.com/pdezwart/php-amqp/blob/24178f3f4f037a6655c99904c159a51a01c0ce8c/amqp_connection_resource.c#L179), the rest of timeouts (write and connection) are there too - write timeout setting has the same logic like read, connection timeout differs while timeout passed to rabbitmq-c's API.

If connection was closed by RabbitMA we can't detect it before actually using socket, which in case it was closed will lead to some sort of `Library error` it may happens when heartbeat used and connection considered to be unreachable by RabbitMQ (two missed hearbeats) and closed by server. Also note, that php-amqp extension written in blocking way, so we don't wait for heartbeats all the time and don't process any of data apart of we explicitly perform any socket read operation (this is most AMQP calls).

I will play with pconnect and timeouts too, but `Library error` is something that hard to investigate from PHP side, can you turn debug logging in RabbitMQ (see our RabbitMQ dev config, [rabbitmq.config:39](https://github.com/pdezwart/php-amqp/blob/3719a973f2ac17d637173309e974a3c09c00f2b3/provision/rabbitmq.config#L39)) and provide relevant part to that failures?

**Comment by pinepain** [comment]
@HarryBird, ok, let's figure out what's going on there.

Please provide following info:

 - platform info (`uname -a`, `lsb_release -a`)
 - php interpreter version (`php -v`)
 - SAPI mode (cli, fpm, cgi, etc) extension is used in
 - php-amqp extension version (`php --ri amqp`) and a way it was installed (pecl, from sources or binaries, if from binaries, post a link to it, if it an option)
 - librabbitmq version and a way it was installed (sources, from distro repo, third-party binaries).

Also provide minimal script to reproduce a problem (it will help a lot).

Note, that there are Vagrant env shipped with this extension, so if you not sure in your env you may try it.

> Any value assign to amqp.read_timeout, I got exception with message "Consumer timeout exceed" immediately.

Can you specify few of that values and run your script with `time` (smth like `time php your_script.php`) to check whether read timeout are even close to what it actually happens. It is not very definitive way to detect a problem, but may raise early alarm faster.

**Comment by sshilko** [comment]
```
{log_levels, [{connection, info}]}
Starting RabbitMQ 3.2.4 on Erlang R16B03-1
```

Getting "Library error: connection closed unexpectedly" (after rabbitmq server restart and w/o restarting php-fpm)
No logs on rabbitmq side for this.

then after restarting php-fom rabbitmq logs show
```
accepting AMQP connection <0.386.0> (...)
```
so persistent connections connected successfuly

then after some time (w/o trying to send anything.. just idle)
```
=ERROR REPORT==== 21-Dec-2015::13:02:46 ===
closing AMQP connection <0.331.0>
{heartbeat_timeout,running}

=ERROR REPORT==== 21-Dec-2015::13:03:05 ===
closing AMQP connection <0.364.0> 
{heartbeat_timeout,running}

=ERROR REPORT==== 21-Dec-2015::13:03:07 ===
closing AMQP connection <0.375.0>
{heartbeat_timeout,running}

=ERROR REPORT==== 21-Dec-2015::13:03:09 ===
closing AMQP connection <0.386.0>
{heartbeat_timeout,running}
```
...

<?php
// ... some code before
try {
    $params = array('host'         => $amqp['host'],
                    'port'         => $amqp['port'],
                    'login'        => $amqp['login'],
                    'password'     => $amqp['password'],
                    'read_timeout'    => 2,
                    'write_timeout'   => 2,
                    'connect_timeout' => 2,
                    'vhost'           => $amqp['vhost'],
                    'heartbeat'       => 20
                    );
                

    $cnn = new AMQPConnection($params);
    $cnn->pconnect();                                

    $ch = new AMQPChannel($cnn);

    $ex = new AMQPExchange($ch);
    $ex->setName(self::EXCHANGE_NAME);
    $ex->setType(self::EXCHANGE_TOPIC);

    #message is json data
    #routing_key is string of format: aaa.bb.ccc
    #params is just type + delivery=non-persistent=1
    $message_params = array('content_type' => 'application/json', 'delivery_mode' => 1);
    
    $ex->publish($message, $routing_key, 0, $message_params);
    //$cnn->disconnect();
} catch (Exception $e) {
    
}
// ... some code after

**Comment by HarryBird** [comment]
**platform info**
```
 ➜  docker@/data/tianhai > uname -a
Linux tianhai 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**php interpreter version**
```
 ➜  docker@/data/tianhai > php -v
PHP 7.0.0 (cli) (built: Dec 17 2015 15:52:33) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

**SAPI mode **
```
cli
```

**php-amqp extension version**
```
 ➜  docker@/data/tianhai > php --ri amqp

amqp

Version => v1.7.0alpha1-master-dev
Revision => 298a867
Compiled => Dec 17 2015 @ 15:38:33
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0-pre
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
```

**librabbitmq version and a way it was installed**
```
git clone git://github.com/alanxz/rabbitmq-c.git
cd rabbitmq-c
git submodule init
git submodule update
autoreconf -i && ./configure && make && make install
git clone https://github.com/pdezwart/php-amqp
phpize && ./configure --with-amqp --with-php-config=/usr/local/php/bin/php-config && make && make install
```

This time i use rabbitmq's official script for test  https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/php-amqp/receive_logs.php 

I only change the host and port like this:

```
<?php
//Establish connection to AMQP
$connection = new AMQPConnection();
$connection->setHost('172.16.21.18');
$connection->setPort(5672);
$connection->setLogin('guest');
$connection->setPassword('guest');
$connection->connect();

//setup channel connection
$channel = new AMQPChannel($connection);

$callback_func = function(AMQPEnvelope $message, AMQPQueue $q) use (&$max_jobs) {
        echo " [x] Received: ", $message->getBody(), PHP_EOL;
        sleep(1);
        $q->nack($message->getDeliveryTag());
};


try {
        //Declare Exchange
        $exchange_name = 'sub_sample';
        $exchange = new AMQPExchange($channel);
        $exchange->setType(AMQP_EX_TYPE_FANOUT);
        $exchange->setName($exchange_name);
        $exchange->declareExchange();


        $queue = new AMQPQueue($channel);
        $queue->setFlags(AMQP_EXCLUSIVE); //allow server to define name
        $queue->declareQueue();
        $queue->bind($exchange_name,$queue->getName());

        echo ' [*] Waiting for logs. To exit press CTRL+C', PHP_EOL;
        $queue->consume($callback_func);

} catch(AMQPQueueException $ex) {
        print_r($ex);
} catch(AMQPExchangeException $ex) {
        print_r($ex);
} catch(AMQPChannelException $ex) {
        print_r($ex);
} catch(AMQPConnectionException $ex) {
        print_r($ex);
} catch(Exception $ex) {
        print_r($ex);
}
$connection->disconnect();
```

My result like this:

```
➜  docker@/data/tianhai/src/rabbitmq-tutorials/php-amqp git:(master) ✗> time php receive_logs.php
 [*] Waiting for logs. To exit press CTRL+C
AMQPQueueException Object
(
    [message:protected] => Consumer timeout exceed
    [string:Exception:private] =>
    [code:protected] => 0
    [file:protected] => /data/tianhai/src/rabbitmq-tutorials/php-amqp/receive_logs.php
    [line:protected] => 41
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /data/tianhai/src/rabbitmq-tutorials/php-amqp/receive_logs.php
                    [line] => 41
                    [function] => consume
                    [class] => AMQPQueue
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Closure Object
                                (
                                    [static] => Array
                                        (
                                            [max_jobs] =>
                                        )

                                    [parameter] => Array
                                        (
                                            [$message] => <required>
                                            [$q] => <required>
                                        )

                                )

                        )
                )

        )

    [previous:Exception:private] =>
)
php receive_logs.php  0.02s user 0.03s system 58% cpu 0.084 total
```

**Comment by pinepain** [comment]
@sshilko, from [Detecting Dead TCP Connections with Heartbeats](https://www.rabbitmq.com/heartbeats.html):

>  Heartbeat frames are sent about every timeout / 2 seconds. After two missed heartbeats, the peer is considered to be unreachable. Different clients manifest this differently but the TCP connection will be closed. When a client detects that RabbitMQ node is unreachable due to a heartbeat, it needs to re-connect. 

As I wrote above, when persistent connection is not in use, php-amqp extension (as well as underlying rabbitmq-c) doesn't not read nor write any data to underlying socket due to being written in synchronous manner (when AMQP is async by it nature). It applied to all incoming data, including heartbeat frames too. So from the first look result you get is expected, but I'm also looking in it by myself right now to. If you still need heartbeats with persistent connections and you have gaps between connection usage, try to increase hearbeat interval to some reasonable for you value (I normally have it set to something close to or even less then 60 second, but it happens that I had to keep it to 20 min (20 * 60 sec) to serve request faster), anyway, I'm looking into the problem now.

**Comment by HarryBird** [comment]
I note a strange detail, I dump my amqp connection
```
<?php


//Establish connection to AMQP
$connection = new AMQPConnection();
$connection->setHost('172.16.21.18');
$connection->setPort(5672);
$connection->setLogin('guest');
$connection->setPassword('guest');
$connection->connect();

var_dump($connection);
exit;
```

```
 ➜  docker@/data/tianhai/src/rabbitmq-tutorials/php-amqp git:(master) ✗> time php receive_logs.php
object(AMQPConnection)#1 (11) {
  ["login":"AMQPConnection":private]=>
  string(5) "guest"
  ["password":"AMQPConnection":private]=>
  string(5) "guest"
  ["host":"AMQPConnection":private]=>
  string(12) "172.16.21.18"
  ["vhost":"AMQPConnection":private]=>
  string(1) "/"
  ["port":"AMQPConnection":private]=>
  int(5672)
 ["read_timeout":"AMQPConnection":private]=>
  int(5672) 
  ["write_timeout":"AMQPConnection":private]=>
  float(0)
  ["connect_timeout":"AMQPConnection":private]=>
  float(0)
  ["channel_max":"AMQPConnection":private]=>
  int(256)
  ["frame_max":"AMQPConnection":private]=>
  int(131072)
  ["heartbeat":"AMQPConnection":private]=>
  int(0)
}
php receive_logs.php  0.02s user 0.03s system 84% cpu 0.064 total
```

Focus the read_timeout line ` ["read_timeout":"AMQPConnection":private]=>int(5672) `, it 's be assign by 5672, that my amqp.port

**Comment by pinepain** [comment]
@HarryBird, yeah, that is already fixed in PR #189 (see https://github.com/pdezwart/php-amqp/pull/189/files#diff-40f7cdf3f96d4346a1418ce7a7af8e92L846 line)

**Comment by pinepain** [comment]
@HarryBird, I just tried [emit_log.php](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/php-amqp/emit_log.php) and [receive_logs.php](https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/php-amqp/receive_logs.php) (both as is, without any modification) with and without that `AMQPConnection::setPort()` fix and it works (even without fix 5672 second for read timeout looks is about hour and a half, so while it is a critical bug, it impact in current context may be interpreted as irrelevant). Can you please try to run non-modified scripts again?

**Comment by sshilko** [comment]
@pinepain thanks, i imagined it works bit different.
will try [preconnect](https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPConnection.php#L162) together with closed connect exception match

**Comment by HarryBird** [comment]
Can you please try to run non-modified scripts again?
=========================

I do not modify anythings except  host & port, because i need connect my rabbitmq server
```
$connection->setHost('172.16.21.18');
$connection->setPort(5672);
```

**Comment by HarryBird** [comment]
I apply the bug fix `AMQPConnection::setPort()` on my workspace and the bug fixed....   :)

**Comment by HarryBird** [comment]
In `receive_logs.php` , AMQPQueue is declare with `AMQP_EXCLUSIVE`.

In `AMQPConnection::setPort()` patch files ` php_amqp.h` 

```
-#define PHP_AMQP_QUEUE_FLAGS        (AMQP_PASSIVE | AMQP_DURABLE | AMQP_EXCLUSIVE | AMQP_AUTODELETE | AMQP_EXCLUSIVE)
+#define PHP_AMQP_QUEUE_FLAGS        (AMQP_PASSIVE | AMQP_DURABLE | AMQP_EXCLUSIVE | AMQP_AUTODELETE)
```

Is this change affect ?

**Comment by pinepain** [comment]
@HarryBird, now I don't understand why it is so :smile:. 
@HarryBird, no, it doesn't, That diff line removes duplicate `AMQP_EXCLUSIVE` from allowed flags bit mask.

**Comment by HarryBird** [comment]
Sorry for I am a new guy for php & C, so i can not supply more detail clues  for debug :sweat_smile:

**Comment by pinepain** [comment]
@sshilko glad to help.

For further readers, the algorithm for persistent connections usage is:

```php
try {
    perform_reading_or_writing_socket_operation();
} catch (Library error) {
    looks_like_socket_closed();
    close_connection_and_open_a_new_one();
    retry_reading_or_writing_socket_operation_without_catching_library_error();
}
```

**Comment by pinepain** [comment]
@HarryBird, that's ok. So new [1.7.0alpha2](https://pecl.php.net/package/amqp) released, thanks to @lstrojny, so if it fixed you problem, mark issue as solved.

**Comment by sshilko** [comment]
@pinepain  Library error: a socket error occurred
```
function xconnect($fresh) {
    $cnn = new AMQPConnection($params);
    if ($fresh)  {
        $cnn->pdisconnect();
    }
    $cnn->pconnect();
    ....
   $ex->publish($message, $routing_key, 0, $message_params);
} 

try {
    xconnect(false);
} catch (...) {
    xconnect(true);
}
```

First time i get ***Library error: connection closed unexpectedly***
second time after trying pdisconnect() i get ***Library error: a socket error occurred***

same with preconnect()

**Comment by HarryBird** [comment]
1.7.0alpha2 had fixed this problem.

Thanks for @pinepain @sshilko

**Comment by pinepain** [comment]
@sshilko problem with persistent connections and stalled connection resource after connection closed by server after missed heartbeats or any library error occurs.

Solution is to force connection closing and free connection resource when any library error occurs while in most cases it means that something significantly unexpected happened which may potentially have negative impact on data integrity and process stability. Fail fast.

I'm working on a fix, estimate is from 24 to 48 hours.

**Comment by pinepain** [comment]
@sshilko, can you please try https://github.com/pinepain/php-amqp/tree/fix_stalled_connection_resource and provide feedback whether it fix the issue and doesn't introduce new one?

**Comment by sshilko** [comment]
@pinepain i can confirm that i no longer see the "socket error occurred" and only expected
***Library error: connection closed unexpectedly***
Which correctly thrown after ***heartbeat_timeout*** rabbitMQ disconnects the client.

I tested by setting heartbeat=1, so rabbitMQ will disconnect persistent connects after 2 seconds.
so now scenario works as-expected, thx!

1. pconnect()
2. try push()
3. if catch exception that matches "connection closed", retry cycle using preconnect() instead

```
amqp

Version => v1.4.0-fix_stalled_connection_resource-dev
Revision => 24dcb18
Compiled => Dec 22 2015 @ 13:39:08
AMQP protocol version => 0-9-1
librabbitmq version => 0.7.1
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

PHP 5.6.16-1+deb.sury.org~precise+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by pinepain** [comment]
@sshilko cool, thanks for reporting and investigating the issue! PR https://github.com/pdezwart/php-amqp/pull/194 addresses this issue.
