### ISSUE TITLE
Best practices for logging use case

### ISSUE THREAD

**Issue by ebuildy** [pdezwart/php-amqp#201]
Hello,

I would like to use it to log all page views (+ business metrics, from Php script), so I mean the queuing stuff must not decrease page loading time.

What the best approach to guarantee that even if queue broker is down, or slow, the Php will not suffer too much ? (something like UDP).

Thanks you,

**Comment by pinepain** [comment]
Hi, you'll probably have to set read/write timeouts low on `AMQPConnection`. It is also reasonable to limit target queue max length/size to prevent running out of resources when consumers fail or messages flow become to high - you should monitor that also, the goal is to consume messages faster then they produced, e.g. even if you have peaks during which messages flow is higher than consumers process them, in avg. you should consume faster.

While `basic.publish` AMQP method is asynchronous, you don't need to wait for response, so the use case is basically establish AMQP connection and then create exchange object and then just publish. You may also want to use persistent connections to save time on handshakes during connection establishing, it is relatively expansive operation in your use case. Note, that you may skip explicit exchange creation (`AMQPExcahnge::declaerExchange()` method call) by creating durable exchange(s) only once, it will also allows you to save few msecs.

**Comment by ebuildy** [comment]
Cool! Thanks you for this help,

I am doing this => https://gist.github.com/ebuildy/51f48bab0b01ed914f64

You are right, removing exchange declaration helps a little.

Is not possible to have something very simple in 1 line:

    queue_send_async("queue", 5672, "my_exchange", "my_queue", "Hello world !");

that could be 100% asyncrhonous?

Thanks again,

**Comment by pinepain** [comment]
In AMQP you send to exchange, and then, based on routing, message may be placed in one or more than one queue and/or other exchange(s), so in your snippet (which, btw, small and can be inserted into your message) can be optimized in a next way (assume you have all necessary exchange, queue and bindings already declared):

```php
$connection = new AMQPConnection([
    'host'     => 'queue',
    'port'     => 5672,
    'login'    => 'guest',
    'password' => 'guest',
    'read_timeout' => 1.0, // set read timeout
    'write_timeout' => 1.0, // set write timeout
    'connect_timeout' => 1.0, // set connect timeout
]);

// $connection->connect(); //  synchronous call
$connection->pconnect(); // use persistent connection, no call in case already persistent connection established
$channel = new AMQPChannel($connection); // synchronous call

// $queue = new AMQPQueue($channel);
// $queue->setName('test-ampq-extension');
// $queue->declareQueue(); // synchronous call

$exchange = new AMQPExchange($channel);
$exchange->setName("exchange-hello-world");
// $exchange->setType(AMQP_EX_TYPE_FANOUT); // makes sense only during exchange declaration
// $exchange->declareExchange();  // synchronous call

// $queue->bind($exchange->getName()); // synchronous call

$exchange->publish('Hello you!' /*, 'your.routing.key'*/);
```

so if you want, you can definitely create some wrapper like you specified, but there are no such functionality out of the box. I edited you snippet to make it contain minimal necessary functionality with specifying sync/async calls, hope it will help.

**Comment by ebuildy** [comment]
Woaaaaa

x3 faster, very cool, many thanks for the help.

**Comment by pinepain** [comment]
@ebuildy if the issue solved, please, close it.
