### ISSUE TITLE
Nested Transactions

### ISSUE THREAD

**Issue by boekkooi** [pdezwart/php-amqp#202]
Hi there,

I was just playing with PHP-AMQP (1.7.0alpha2 and master) and RabbitMQ's (3.6.0) transaction. (PHP 7.0.2) 

The problem is that I was wondering if nested transactions would work so I wrote a little test script (see below) but the behaviour seems a little unexpected.

I was hoping for the expectation provided in the test below (2 items in queue and rolled back) or at least a exception or false on the second `startTransaction` indicating that nested transactions are not possible. Instead everything is green but only the last publish is kept because the `rollbackTransaction` roles everything back. 

I hope you or someone can take a look at this.

Thanks in advance!

```PHP
--TEST--
AMQP Nested transactions
--SKIPIF--
<?php
if (!extension_loaded("amqp")) print "skip";
?>
--FILE--
<?php

$queryName = 'test-' . microtime(true);

$cnn = new AMQPConnection(array('read_timeout' => 5));
$cnn->connect();

$ch = new AMQPChannel($cnn);

$ex = new AMQPExchange($ch);
$ex->setName("exchange-" . microtime(true));
$ex->setType(AMQP_EX_TYPE_FANOUT);
$ex->declareExchange();

$queue = new AMQPQueue($ch);
$queue->setName($queryName);
$queue->setFlags(AMQP_AUTODELETE);
$queue->declareQueue();
$queue->bind($ex->getName());

echo 'Start: ' . ($ch->startTransaction() ? "true" : "false"), PHP_EOL;

$ex->publish('valid', $queryName);

echo 'Start: ' . ($ch->startTransaction() ? "true" : "false"), PHP_EOL;

$ex->publish('invalid', $queryName);

echo 'Rollback: ' . ($ch->rollbackTransaction() ? "true" : "false"), PHP_EOL;

$ex->publish('valid', $queryName);

echo 'Commit: ' . ($ch->commitTransaction() ? "true" : "false"), PHP_EOL;

echo PHP_EOL;

$msg = $queue->get();
echo 'Consume:', PHP_EOL;
var_dump($msg->getBody());

$msg = $queue->get();
echo 'Consume:', PHP_EOL;
var_dump($msg->getBody());

--EXPECT--
Start: true
Start: true
Rollback: true
Commit: true

Consume:
string(5) "valid"
Consume:
string(5) "valid"
```

**Comment by boekkooi** [comment]
Ok so here are some more tests that seem a little off

```PHP
--TEST--
AMQP Transactions commit valid once
--SKIPIF--
<?php
if (!extension_loaded("amqp")) print "skip";
?>
--FILE--
<?php

$cnn = new AMQPConnection(array('read_timeout' => 5));
$cnn->connect();

$ch = new AMQPChannel($cnn);

echo 'Start: ' . ($ch->startTransaction() ? "true" : "false"), PHP_EOL;

echo 'Commit: ' . ($ch->commitTransaction() ? "true" : "false"), PHP_EOL;
echo 'Commit: ' . ($ch->commitTransaction() ? "true" : "false"), PHP_EOL;

--EXPECT--
Start: true
Commit: true
Commit: false
```

```PHP
--TEST--
AMQP Transactions rollback is valid once
--SKIPIF--
<?php
if (!extension_loaded("amqp")) print "skip";
?>
--FILE--
<?php

$cnn = new AMQPConnection(array('read_timeout' => 5));
$cnn->connect();

$ch = new AMQPChannel($cnn);

echo 'Start: ' . ($ch->startTransaction() ? "true" : "false"), PHP_EOL;

echo 'Rollback: ' . ($ch->rollbackTransaction() ? "true" : "false"), PHP_EOL;
echo 'Rollback: ' . ($ch->rollbackTransaction() ? "true" : "false"), PHP_EOL;

--EXPECT--
Start: true
Rollback: true
Rollback: false
```

**Comment by pinepain** [comment]
Nested transactions is not something from AMQP protocol. Channel can be regular one OR transactional OR in confirmation mode (which I'm working on right now). According to AMQP spec `tx.start` can be called more than once, but it doesn't says anything that such calls will lead to nested transaction. After each `tx.rollback` or `tx.commit` new transactions starts, so literally, once channel put into transactional mode it stay in this mode until get closed.

**Comment by boekkooi** [comment]
@pinepain Thanks for the quick response and damn that works every different then I was expecting....

**Comment by pinepain** [comment]
@boekkooi you can ask more about nested transactions (if any) in [official RabbitMQ user group](https://groups.google.com/forum/#!forum/rabbitmq-users) but I'm pretty sure it doesn't support it. AMQP protocol wouln'd or at least shouldn't miss such major feature description or at least note. Anyway, if it appears that I'm wrong, please let me know.
