### ISSUE TITLE
Add support for arguments on consume()

### ISSUE THREAD

**Issue by olemartinorg** [pdezwart/php-amqp#204]
I see that ```\AMQPQueue::consume()``` does not have an ```$arguments``` argument, or similar. According to the [AMQP reference](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.consume) it should be possible to pass arbitrary arguments to the broker. I would like to use this for [RabbitMQ Consumer Priorities](https://www.rabbitmq.com/consumer-priority.html), but php-amqp doesn't seem to support that.

**Comment by pinepain** [comment]
Arguments are set via `AMQPQueue::setArgument()` and `\AMQPQueue::setArguments()` methods. It's a bit crazy and not obvious at all, but it works.

**Comment by lstrojny** [comment]
Closing for now

**Comment by olemartinorg** [comment]
Oh, I looked (but probably I didn't look closely enough). Thanks a bunch!
