### ISSUE TITLE
Returns wrong PHP_AMQP_VERSION on git

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#206]
This line 
    
    "`git describe --abbrev=0 --tags`-`git rev-parse --abbrev-ref HEAD`-dev"

returns 

    "v1.4.0-master-dev"

executed from current mater. 

see: https://github.com/pdezwart/php-amqp/blob/master/config.m4#L115

This leads to minimum requirements of php amqp version are not fulfilled for composer when I use php-amqp from master.

**Comment by pinepain** [comment]
What is your `git branch` and `git tag` output? Normally, fetching all data from remote should solve the problem: `git fetch` should fix wrong output.

**Comment by prolic** [comment]
Damn, my bad. I only fetch your repo, not the original from pdezwart ;)

Sorry
