### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by ddtraceweb** [pdezwart/php-amqp#212]
hi,

i have this error on debian squeeze 7, php 5.5.30, can you help me ?

configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/install/pear-build-rootexIN7E/amqp-1.6.1/libtool --mode=compile cc  -I. -I/tmp/pear/install/amqp -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-rootexIN7E/amqp-1.6.1/include -I/tmp/pear/install/pear-build-rootexIN7E/amqp-1.6.1/main -I/tmp/pear/install/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/install/amqp/amqp.c -o amqp.lo
libtool: compile:  cc -I. -I/tmp/pear/install/amqp -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-rootexIN7E/amqp-1.6.1/include -I/tmp/pear/install/pear-build-rootexIN7E/amqp-1.6.1/main -I/tmp/pear/install/amqp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/install/amqp/amqp.c  -fPIC -DPIC -o .libs/amqp.o
In file included from /tmp/pear/install/amqp/amqp.c:46:0:
/tmp/pear/install/amqp/php_amqp.h:346:2: error: unknown type name 'amqp_socket_t'
/tmp/pear/install/amqp/amqp.c: In function 'php_amqp_long_string':
/tmp/pear/install/amqp/amqp.c:732:10: error: 'amqp_empty_bytes' undeclared (first use in this function)
/tmp/pear/install/amqp/amqp.c:732:10: note: each undeclared identifier is reported only once for each function it appears in
/tmp/pear/install/amqp/amqp.c: In function 'internal_convert_zval_to_amqp_table':
/tmp/pear/install/amqp/amqp.c:842:27: error: 'amqp_empty_bytes' undeclared (first use in this function)
make: *** [amqp.lo] Error 1
ERROR: `make' failed

**Comment by zaq178miami** [comment]
Hi. What is php-amqp version do you use and what is rabbitmq-c (librabbitmq) version do you have installed?

**Comment by ddtraceweb** [comment]
hi,

it's the version 1.6.1 that i taking form pear, and the last version of librabbitmq-dev

**Comment by pinepain** [comment]
Please, post full log. Also, please, post exact librabbitmq version do you have, I can't get from that log what is it. Also, make sure no other rabbitmq-c version installed.

It may come in handy to follow [Things to check before reporting a problem](https://github.com/pdezwart/php-amqp#things-to-check-before-reporting-a-problem) from [How to report a problem](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) readme section. Also, if it's an option for you, try to use latest php-amqp version (at the time of writing it is 1.7.0alpha2, don't worry that it's marked as beta).

**Comment by lstrojny** [comment]
Closing, no response.
