### ISSUE TITLE
No method on a channel to close it.

### ISSUE THREAD

**Issue by bweston92** [pdezwart/php-amqp#216]
`AMQPChannel::close()` would be great. I see the code in there for closing the channel but not any good in C so will request it from you guys. Thanks.

**Comment by pinepain** [comment]
Channel become opened in constructor and closed in destructor or when channel or connection error occurs. At this time there are no plans to change that. What's you use case for that?

**Comment by bweston92** [comment]
Because the channels even after unset($channel) doesn't close/free the channel on rabbitmq.

---Sent from Boxer | http://getboxer.com

On 21 April 2016 at 20:47:17 BST, Bogdan Padalko <notifications@github.com> wrote:Channel become opened in constructor and closed in destructor or when channel or connection error occurs. At this time there are no plans to change that. What's you use case for that?  —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by pinepain** [comment]
If there any refences left PHP object won't be destroyed, in case of php-amqp it is common to see something like this:

```php
$conn = new AMQPConnection();
$conn->connect();

$ch = new AMQPChannel($conn); // $ch refcount=1

$q = new AMQPQueue($ch); // $ch refcount=2

unset($ch);  // $ch refcount=1
``` 

so in such scenario channel still exists while it is in use by queue. In this case closing channel will break queue usage, so it is a bit pointless to do that. Is it an option for you to cleanup all entities that utilizes channel?

**Comment by bweston92** [comment]
Ok, I thought the queue would of de constructed too. Will give it a go.

**Comment by bweston92** [comment]
The following doesn't close the channel.

```
    /**
     * @param Command|array $command
     */
    public function __invoke(AMQPConnection $connection, $command)
    {
        if (! $connection->isConnected()) {
            $connection->connect();
        }

        $channel = new \AMQPChannel($connection);
        $exchange = new \AMQPExchange($channel);
        $exchange->setFlags(AMQP_DURABLE);
        $exchange->setName('commands');
        $exchange->setType('direct');
        $exchange->declareExchange();

        $exchange->publish($this->commandToJson($command), $this->commandQueue);

        unset($exchange);
        unset($channel);
    }
```

**Comment by prolic** [comment]
can be closed now.
