### ISSUE TITLE
Please tag a stable release compatible with PHP 7

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#217]
PHP 7 is supported only in the 1.7 versions, which are only available as alpha releases.
I' looking at providing the amqp extension for the heroku php buildpack, but shipping alpha versions there won't be accepted.

**Comment by lstrojny** [comment]
Will do very soon.

**Comment by lstrojny** [comment]
1.7.0 released.

**Comment by stof** [comment]
great. Thanks
