### ISSUE TITLE
Reliable release schedule

### ISSUE THREAD

**Issue by lstrojny** [pdezwart/php-amqp#219]
Currently we have a rather erratic release schedule which doesn't really fit the popularity of the package and what our users should expect from us. That being said, it’s nobody’s fault but mine.

In order to fix that I propose a consistent, monotonous and reliable release train model where we ship 4 minor versions a year plus as many patch versions as we need. 4 weeks before each release we would be releasing the first release candidate version and release as many more RCs as we need to stabilize. Additionally we would be committing to maintain two versions, the current and the previous version.

This is the proposed timeline:
- 2016-05-21, Sat: Release of 1.8.0RC1
- 2016-06-18, Sat: Release of 1.8.0
- 2016-06-18, Sat: No EOL (transitioning phase)
- 2016-08-20, Sat: Release of 1.10.0RC1
- 2016-09-17, Sat: Release of 1.10.0
- 2016-09-17, Sat: End of life 1.7 series (special EOL as we are in the transitioning phase)
- 2016-11-19, Sat: Release of 1.12.0RC1
- 2016-12-17, Sat: Release of 1.12.0
- 2016-12-17, Sat: End of life 1.8 series
- 2017-02-18, Sat: Release of 2.0.0RC1
- 2017-03-18, Sat: Release of 2.0.0
- 2017-03-18, Sat: End of life 1.10 series
- 2017-05-20, Sat: Release of 2.2.0RC1
- 2017-06-17, Sat: Release of 2.2.0
- 2017-06-17, Sat: End of life 1.12 series
- 2017-08-19, Sat: Release of 2.4.0RC1
- 2017-09-16, Sat: Release of 2.4.0
- 2017-09-16, Sat: End of life 2.0 series
- 2017-11-18, Sat: Release of 2.6.0RC1
- 2017-12-16, Sat: Release of 2.6.0
- 2017-12-16, Sat: End of life 2.2 series
- 2018-02-17, Sat: Release of 3.0.0RC1
- 2018-03-17, Sat: Release of 3.0.0
- 2018-03-17, Sat: End of life 2.10 series
- 2018-05-19, Sat: Release of 3.2.0RC1
- 2018-06-16, Sat: Release of 3.2.0
- 2018-06-16, Sat: End of life 2.12 series
- 2018-08-18, Sat: Release of 3.4.0RC1
- 2018-09-15, Sat: Release of 3.4.0
- 2018-09-15, Sat: End of life 3.0 series

@pinepain, et al, let me know what you think!
### Release date calculation script

``` php
<?php
namespace PhpAmqp;

use DateInterval;
use DateTimeImmutable;

function d($string) : DateTimeImmutable { return new DateTimeImmutable($string); }

function days_between(DateTimeImmutable $left, DateTimeImmutable $right) : int { return $left->diff($right)->days; }

function break_days(int $days, int $parts) : int { return $days / $parts; }

function major_version(DateTimeImmutable $date) : int { return (int) $date->format('Y') - 2016 + 1; }

function minor_version(DateTimeImmutable $date) : int {
    static $minorVersionMap = [2016 => 6];

    $year = $date->format('Y');

    return $minorVersionMap[$year] = isset($minorVersionMap[$year]) ? $minorVersionMap[$year] + 2 : 0;
}

function version_every(int $days, DateTimeImmutable $date, $limit) {
    yield $date;

    for ($a = 0; $a < $limit - 1; $a++) {
        yield $date = $date->add(new DateInterval('P' . $days . 'D'));
    }
}

function print_release(DateTimeImmutable $date, $major, $minor, $patch, $suffix = '') {
    printf("%s: Release of %s.%s.%s%s\n", $date->format('Y-m-d, D'), $major, $minor, $patch, $suffix);
}

function print_eol(DateTimeImmutable $date, $major, $minor) {
    printf("%s: End of life %s.%s series\n", $date->format('Y-m-d, D'), $major, $minor);
}

function main() {
    $numberOfDaysBetweenReleases = break_days(
        days_between(d(START_OF_RELEASE_YEAR), d(START_OF_RELEASE_YEAR)->modify('+1 YEAR')),
        RELEASES_PER_YEAR
    );

    foreach (version_every($numberOfDaysBetweenReleases, d(START_OF_RELEASE_YEAR), 10) as $date) {
        $major = major_version($date);
        $minor = minor_version($date);
        print_release($date, $major, $minor, 0, 'RC1');
        print_release($date->modify('+4 weeks'), $major, $minor, 0);
        print_eol(
            $date->modify('+4 weeks'),
            $minor - 4 >= 0 ? $major : $major - 1,
            $minor - 4 >= 0 ? $minor - 4 : $minor - 4 + 14
        );
    }
}

const RELEASES_PER_YEAR = 4;
const START_OF_RELEASE_YEAR = 'May 21th 2016';
main();
```

**Comment by hanikesn** [comment]
Hey, this schedule seems a bit optimistic regarding breaking BC. As a lot of people will be stuck on older versions because of various LTS releases:

https://wiki.ubuntu.com/LTS
http://symfony.com/doc/current/contributing/community/releases.html

That means people are dependent on the version of the extension that's installed by the distro of their choice and of various php helper libraries and they have to be kept in sync. So I fear that this would fragment the community a lot because upgrading gets harder or alienate people to use a more stable solution.

**Comment by lstrojny** [comment]
@hanikesn thanks for your feedback. The alternative then would be to either maintain a release for a year, which should suffice. Then the question is, is it realistic to maintain four releases at a time or if it’s better to only ship two minor versions.

**Comment by pinepain** [comment]
@lstrojny As to current release schedule, it's not perfect but no need to find whose fault is that. No need to blame anybody, especially yourself. It's nobody fault, it's done when it's done. We had one or two delays but it happens. This is pretty small project with not so large committers base, so that was expected. 

As to proposed timeline, I have following questions:
 1. Do we have roadmap?
   1. Do we suppose to have enough features and changes for next major release (2.0).
 2. Are we going to move away from semantic versioning?
  1. Do we have numbers how many projects/users use php-amqp extension on their daily basis or can we figure it out somehow, even approximately?

**Comment by lstrojny** [comment]
For your questions:

 - For the roadmap, not yet, but that for me would be step two after deciding on a monotonous release. I would see it pragmatically: if we don't have enough for a 2.0, let’s ship a 1.14 instead
 - Semantic versioning: I would stick with it. How the version number is incremented should be decided based on what’s in
 -- The best we can have is download numbers, as seen here: https://pecl.php.net/package-stats.php?pid=879&rid=&cid=16. I have no idea how that translates into usage but given opened issues, it doesn’t seem too small.

**Comment by pinepain** [comment]
Wow, have not seen that numbers before! They are indeed not small at all! I guess we may also somehow take into account apt/rpm packages downloads statistics, if any. Anyway, numbers are pretty large.

What is the purpose to increment minor version by 2? Do you plan to have even versions to be stable and odd unstable?

I don't get proposed release model in full. What about just clarifying current release model to specify due dates, like timeline from PR to release (alpha/beta -> stable), e.g. for bugfix we commit to release new patch release (alpha/beta -> stable) in a no more than 1 week after approval, for functional changes we commit to roll new testing release (alpha/beta) in a no more than 2 week and if no bug reports in a 1 month (may be less) it considered to be stable and we release new minor version (alpa/beta -> RC -> stable).

As to maintaining two version at the same time, I guess it's not very common case for minor versions, at least for small projects like this one. In case there are large minor release with some bugfixes that should be backported, we backport bugfixes/features to current stable version, but right after new stable appears we do not touch previous stable in any way. Sure, this doesn't applicable to major releases, but we have only one major version for now, which makes life easier.

@lstrojny what is your thoughts about such model? It doesn't seem to differ too much from what we have now, but do we have to differ?

**Comment by lstrojny** [comment]
Closing for now
