### ISSUE TITLE
Segfault with 1.7.0

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#220]
Hi,

I currently run into seg faults with amqp 1.7.0. The problem is gone when I compile myself from master branch.

Can you release a bugfix release? No further investigation is needed, as it's fixed in master.

Thanks

**Comment by pinepain** [comment]
Can you provide more detail and provide reproducible example to cause a segfault? Maybe, fork and push your test case to travis (please, leave only the necessary php version in build matrix).

**Comment by prolic** [comment]
this can be closed now, fixed in 1.7.1.
thanks
