### ISSUE TITLE
AMQPQueueException: Consumer timeout exceed

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#223]
I have the following use case:

I consume multiple messages and ack the whole block at once.
When I ack every 3 messages, everything is okay.
When I ack every 4 messages, I get the AMQPQueueException: Consumer timeout exceed.

I increased the read_timeout, write_timeout, connection_timeout and heart_beat, nothing helped.

Any ideas?

**Comment by pinepain** [comment]
Hi, looks like a bug.

Can you post producer and consumer code to test this behavior? Also please specify PHP, RabbitMQ, php-amqp and rabbitmq-c version and how they were installed. I saw you already posted some of these info in other reports, so just clarify what missed.

I'm a bit overcommitted last time, so it may take me a while to get to all these reports. Sorry for that.

**Comment by prolic** [comment]
To reproduce see here:

https://github.com/prolic/HumusAmqp/blob/master/tests/AbstractCallbackConsumerTest.php#L178

changing the value from 3 to 4 will lead to the error shown above.

Current setup:
php-amqp from master
rabbitmq-c from master
RabbitMQ 3.5.4
PHP 7.0.3

**Comment by prolic** [comment]
Test-script:

    $c = new AMQPConnection(['read_timeout' => 3, 'write_timeout' => 3]);
    $c->connect();
    
    $ch = new AMQPChannel($c);
    
    $ex = new AMQPExchange($ch);
    $ex->setName('test-exchange');
    $ex->setType('direct');
    $ex->declareExchange();
    
    $q = new AMQPQueue($ch);
    $q->setName('test-queue');
    $q->setFlags(AMQP_DURABLE);
    $q->declareQueue();
    $q->bind('test-exchange');
    
    $ex->publish('message #1');
    $ex->publish('message #2');
    $ex->publish('message #3');
    $ex->publish('message #4');
    $ex->publish('message #5');
    $ex->publish('message #6');
    $ex->publish('message #7');
    $ex->publish('message #8');
    $ex->publish('message #9');
    $ex->publish('message #10');
    $ex->publish('message #11');
    $ex->publish('message #12');
    $ex->publish('message #13');
    $ex->publish('message #14');
    $ex->publish('message #15');
    $ex->publish('message #16');
    
    $cnt = 0;
    
    try {
        $q->consume(
            function (AMQPEnvelope $envelope) use (&$cnt, &$result, $q) {
                var_dump($envelope->getBody());
                $cnt++;
                if ($cnt % 8 == 0) {
                    var_dump('acked all');
                    $q->ack($envelope->getDeliveryTag(), AMQP_MULTIPLE);
                }
            }
        );
    } catch (AMQPQueueException $e) {
        var_dump($e->getMessage());
    }

But changing the line `if ($cnt % 8 == 0) {` to `if ($cnt % 2 == 0) {` works!

**Comment by prolic** [comment]
I found out this a not a bug!

```
$ch->setPrefetchCount(8);
```

was missing.
