### ISSUE TITLE
Delete unknown exchange leads to seg fault

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#226]
Example script:

    $c = new AMQPConnection();
    $c->connect();
    $ch = new AMQPChannel($c);
    $ex = new AMQPExchange($ch);
    var_dump($ex->delete());

    16346 segmentation fault (core dumped)

**Comment by pinepain** [comment]
Please, add info about what PHP, php-amqp, librabbitmq and RabbitMQ versions do you use and a way they were installed. Also please specify you OS and platform.

**Comment by prolic** [comment]
PHP 7.0.3
php-amqp self-compiled from current master
librabbitmq self-compiled from current master
RabbitMQ 3.5.4, Erlang 18.0
Ubuntu 15.10
Platform: x86_64

**Comment by pinepain** [comment]
Confirmed. The reason is `PHP_AMQP_READ_THIS_PROP_STR()` macro usage on non-string properties. Working on a fix.
