### ISSUE TITLE
Question about channel behaviour

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#227]
When I consume messages from the queue with `AMQPQueue->consume()` after specified `read_timeout` I receive `Consumer timeout exceed` exception. When I catch that exception, I cannot call `AMQPQueue->consume()` again, but I can still ack / nack messages.
Is this behaviour wanted?
Btw: I cannot do the same with php-amqplib, after connection timeout ack / nack is not working there.

**Comment by pinepain** [comment]
Looks strange. To make sure I got you right, can you provide minimal example to demonstrate the behavior.

**Comment by prolic** [comment]
Edit: In php-amqplib I can ack/ nack messages after timeout in consume(). My previous comment about php-amqplib was wrong.

While trying to write a test-script, I can see the bug was on my side, all good. Going to close.
