### ISSUE TITLE
No message in queue after consume timeout and reject with requeue

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#229]
In words:

I send 2 messages to an exchange, they are routed to a queue.
I consume messages from there, without acknowledgement.
After specified read timeout the queue throws a timeout exception.
After consumer timeout I nack all and requeue them.

Then I need to call $queue->cancel($consumerTag), without this the messages are still delivered to the queue, even if it's no longer consuming (there was a consumer timeout exception !) - why is that? I don't know. But when this is the rule, I can live with it.

But when I now access the queue and try to fetch a single messages, the message is very often not there (you need to run the test script multiple times with different results).

Now to code:

    $c = new AMQPConnection(['read_timeout' => 1, 'write_timeout' => 1]);
    $c->connect();
    
    $ch = new AMQPChannel($c);
    
    $ex = new AMQPExchange($ch);
    $ex->setName('test-exchange');
    $ex->setType('direct');
    $ex->declareExchange();
    
    $q = new AMQPQueue($ch);
    $q->setName('test-queue');
    $q->setFlags(AMQP_DURABLE);
    $q->declareQueue();
    $q->bind('test-exchange');
    
    $q->purge(); // only for running this script multiple times
    
    $ex->publish('message #1');
    $ex->publish('message #2');
    $cnt = 0;
    
    $consumerTag = uniqid();
    $lastDeliveryTag = null;
    
    try {
        $q->consume(
            function (AMQPEnvelope $envelope) use (&$lastDeliveryTag) {
                var_dump($envelope->getBody());
                $lastDeliveryTag = $envelope->getDeliveryTag();
            },
            AMQP_NOPARAM,
            $consumerTag
        );
    } catch (\Exception $e) {
        var_dump($e->getMessage());
    }
    
    $q->nack($lastDeliveryTag, AMQP_MULTIPLE|AMQP_REQUEUE);
    $q->cancel($consumerTag); // why is this needed at all?
    
    sleep(2); // even with sleep I receive boolean instead of object of $q->get()
    
    $m = $q->get();
    var_dump(gettype($m));

No let's change the test-script a little:

    $c = new AMQPConnection(['read_timeout' => 1, 'write_timeout' => 1]);
    $c->connect();

    $ch = new AMQPChannel($c);

    $ex = new AMQPExchange($ch);
    $ex->setName('test-exchange');
    $ex->setType('direct');
    $ex->declareExchange();

    $q = new AMQPQueue($ch);
    $q->setName('test-queue');
    $q->setFlags(AMQP_DURABLE);
    $q->declareQueue();
    $q->bind('test-exchange');

    $q->purge(); // only for running this script multiple times

    $ex->publish('message #1');
    $ex->publish('message #2');
    $cnt = 0;

    $consumerTag = uniqid();
    $lastDeliveryTag = null;

    try {
        $q->consume(
            function (AMQPEnvelope $envelope) use (&$lastDeliveryTag) {
                var_dump($envelope->getBody());
                $lastDeliveryTag = $envelope->getDeliveryTag();
            },
            AMQP_NOPARAM,
            $consumerTag
        );
    } catch (\Exception $e) {
        var_dump($e->getMessage());
    }

    $q->nack($lastDeliveryTag, AMQP_MULTIPLE|AMQP_REQUEUE);

    $q->getConnection()->reconnect(); // channel close would be nicer !!!

    $c = new AMQPConnection(['read_timeout' => 1, 'write_timeout' => 1]);
    $c->connect();

    $ch = new AMQPChannel($c);

    $ex = new AMQPExchange($ch);
    $ex->setName('test-exchange');
    $ex->setType('direct');
    $ex->declareExchange();

    $q = new AMQPQueue($ch);
    $q->setName('test-queue');
    $q->setFlags(AMQP_DURABLE);
    $q->declareQueue();
    $q->bind('test-exchange');

    $m = $q->get();
    var_dump(gettype($m));

Differences:

* $queue->cancel($consumerTag) is no longer needed, this is good!
* As there is no method like $channel->close() I need to reconnect on the connection in order to destroy the channel.
* I need to recreate the channel (that's ok)
* I need to recreate the queue (that's bad, but working)

So when there is no bug in this library and I got everything right, a $channel->close() method is very important to me.

Related to: https://github.com/pdezwart/php-amqp/issues/216

**Comment by prolic** [comment]
Note: While the first script is failing on `$queue->get()` (returning false instead of AMQPEnvelope) sometimes, the second script works good, but recreating connection instead of being able to call $channel->close() is bad.

**Comment by prolic** [comment]
Any news? `$channel->close()` would really help a lot here. Can this be added soon?

**Comment by pinepain** [comment]
@prolic Thanks for reminding. Sorry that that it took so long, here is [PR for this](https://github.com/pdezwart/php-amqp/pull/250).

Can you please test whether it?

**Comment by prolic** [comment]
tested and works like a charm!
