### ISSUE TITLE
Problem with $channel->setConfirmCallback

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#231]
The message signature is:

    setConfirmCallback(
        function (int $deliveryTag, bool $multiple = false) : bool, 
        function (int $deliveryTag, bool $multiple, bool $requeue) : bool
    )

The problem is, I cannot really do much with it.

An example:

I produce a single message and want to see, if it is published correctly, in this case the method is very useful. But when I produce 10 messages and want to see, if they are published correctly. Now there is a problem:
* I could get a confirmCallback for every 10 messages, that would be ok.
* I could get a confirmCallback for the first 5 messages and $mulitple true, and for the last 5 messages and $multiple true. That means for me, I can tell that 2 times multiple messages are published correctly, meaning at least 4. But I cannot tell, if this was 10 or only 4. That's why I cannot decide whether or not to exit the wait loop.

**Comment by pinepain** [comment]
Can you clarify more, it's not clear what's your problem. `$deliveryTag` will hold sequence number and `$multiple` will hold whether single message confirmed or all message up to and including that one with `$deliveryTag` are confirmed. This is how [Confirms (aka Publisher Acknowledgements)](https://www.rabbitmq.com/confirms.html) works.

**Comment by prolic** [comment]
Assuming I have multiple processes publishing messages to an exchange.
When I publish 5 messages from a process, I cannot know upfront which `$deliveryTags`'s they'll receive. So when I get the information that `$deliveryTag` = 111 was received with $multiple, what does that say to me? I don't know if my messages have delivery tag 106-111 or 99, 102, 105, 111, 130.

**Comment by pinepain** [comment]
It's basically client responsibility to keep track of delivery tags.

Delivery tag starts from 1 and is a 64 bit integer, so max value is 9223372036854775807 (`PHP_INT_MAX` on x64 platform, btw). Delivery tag is unique inside specific channel.

That mean that when you publish you already know what deliver tag message will hold. Java have [`Channel.getNextPublishSeqNo()`](https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.5.1/rabbitmq-java-client-javadoc-3.5.1/com/rabbitmq/client/Channel.html#getNextPublishSeqNo%28%29) method to receive next delivery tag value. With php-amqp you'll have to do that manually, at least at this time.

**Comment by prolic** [comment]
Ah ok, this clarifies a lot. I was thinking the delivery tag is given on the server. My fault.

**Comment by pinepain** [comment]
Yeah, this is a bit tricky moment.
