### ISSUE TITLE
bug_gh155_direct_reply_to.phpt failure

### ISSUE THREAD

**Issue by carlwgeorge** [pdezwart/php-amqp#232]
I am running into a test suite failure with the following setup:

amqp 1.7.0
PHP 7.0.7 (from [IUS](https://ius.io))
librabbitmq 0.5.2 (from [EPEL](https://fedoraproject.org/wiki/EPEL))
CentOS 7

```
TEST 119/128 [tests/bug_gh155_direct_reply_to.phpt]
========DIFF========
001+ Fatal error: Uncaught AMQPQueueException: Server channel error: 404, message: NOT_FOUND - no queue 'amq.rabbitmq.reply-to' in vhost '/' in /home/carl/amqp/amqp-1.7.0/tests/bug_gh155_direct_reply_to.php:11
002+ Stack trace:
003+ #0 /home/carl/amqp/amqp-1.7.0/tests/bug_gh155_direct_reply_to.php(11): AMQPQueue->consume(NULL, 128)
004+ #1 {main}
005+   thrown in /home/carl/amqp/amqp-1.7.0/tests/bug_gh155_direct_reply_to.php on line 11
001- Publishing request...
002- Reply-to queue: amq.rabbitmq.reply-to.%s.%s==
003- Prepare response queue...
004- Publishing response...
005- Waiting for reply...
006- response: amq.rabbitmq.reply-to.%s.%s==
007- Received on amq.rabbitmq.reply-to queue
008- done
========DONE========
FAIL #155 RabbitMQ's Direct reply-to (related to consume multiple) [tests/bug_gh155_direct_reply_to.phpt]
```

**Comment by pinepain** [comment]
What RabbitMQ version do you use?

**Comment by carlwgeorge** [comment]
That is with RabbitMQ 3.3.5 from [EPEL](https://fedoraproject.org/wiki/EPEL).

**Comment by pinepain** [comment]
[Direct reply-to](https://www.rabbitmq.com/direct-reply-to.html) (aka Fast RPC Replies) available starting from RabbitMQ 3.4.0, see [changelog](https://www.rabbitmq.com/changelog.html) for details.

**Comment by carlwgeorge** [comment]
Roger that.  Is there a way to detect the server version within PHP as part of the SKIPIF statement?

**Comment by pinepain** [comment]
Less likely it is possible to do in a sane way. The closest to what we may use here is [XFAIL](http://qa.php.net/phpt_details.php#xfail_section) section which just let some test fail. I personally don't like it while it servers different purposes than we need here.

**Comment by carlwgeorge** [comment]
Understandable, thanks for the feedback.  I'll patch locally to skip that test when building on EL7 with the older server version.

Is there an appropriate place to document the minimum server version required for the test suite?

**Comment by pinepain** [comment]
I guess somewhere in the readme, probably in a requirements section, I made a tiny PR for that, see #234. //cc @lstrojny

**Comment by lstrojny** [comment]
Thanks!
