### ISSUE TITLE
Error in amqp_connection.c leads to wrong amqp.password value

### ISSUE THREAD

**Issue by skobkars** [pdezwart/php-amqp#238]
Hi,

Line 362 of amqp_connection.c takes length of 'amqp.login' instead of 'amqp.password':

STR("amqp.password"), (PHP5to7_param_str_len_type_t) (strlen(INI_STR("amqp.password")) > 128 ? 128 : strlen(INI_STR("**amqp.login**"))) TSRMLS_CC);

Thus, if password is longer than login name, the former gets truncated.

**Comment by prolic** [comment]
Can be closed, too

**Comment by skobkars** [comment]
Resolved and closed. Thanks everyone.
