### ISSUE TITLE
Problem with persistent connection

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#240]
AMQPConnectionException: There are already established persistent connection to the same resource.

**Comment by prolic** [comment]
How to solve this?

**Comment by pinepain** [comment]
Can you please provide php-amqp, PHP, RabbitMQ and rabbitmq-c versions do you use? Also, please provide test script to reproduce a problem. Also have a look at [How to report a problem](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) readme section.

**Comment by prolic** [comment]
I am using PHP7, rabbitmq-c v0.7.1, php-amqp compiled from master and RabbitMQ 3.5.7.
I created a test-repo with failing unit tests here:
https://github.com/prolic/php-amqp-test
The failing travis build is here:
https://travis-ci.org/prolic/php-amqp-test/builds/144668488

The test is basically:
```
    $connection = new \AMQPConnection();
    $connection->pconnect();

    $connection2 = new \AMQPConnection();
    $connection2->pconnect();
```

**Comment by prolic** [comment]
This is only to demonstrate that I cannot use persistent connections in unit tests.

**Comment by pinepain** [comment]
You can't have more than one persistent connection to the same resource, see the test in my reply above and [`php_amqp_get_connection_hash()`](https://github.com/pdezwart/php-amqp/blob/master/amqp_connection.c#L98) to see what connection options affect persistent connection hash (basically, all options except timeouts).

So you have to reuse already opened persistent connection or close it or open new persistent connection with different option, e.g.

```php
    $connection = new \AMQPConnection(['channel_max' => 100]); 
    $connection->pconnect();

    $connection2 = new \AMQPConnection(['channel_max' => 101]);
    $connection2->pconnect();
```

Normally max channels number is 65535, which can be seen in `php --ri amqp` output as "Default max channels per connection". 100 is more than enough, you won't usually have more than 100 opened channels at the same in your tests. In case you do, you may use values under 65535.

**Comment by prolic** [comment]
I see. Thank you.
