### ISSUE TITLE
Confirm select slower then transaction

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#241]
Confirm select mode is supposed to be faster than a transaction on amqp, but this is not the case with this extension.

Here are some timing tests with 10.000 messages:

just publish: float(0.04935884475708)

transaction: float(0.13030695915222)

confirm select: float(0.15289998054504)

You can see the test here: https://github.com/prolic/php-amqp-test/tree/publish_timing

And timing results from travis here: https://travis-ci.org/prolic/php-amqp-test/builds/144671757

**Comment by pinepain** [comment]
Hi, thanks for pointing on this! 

`AMQPChannel::waitForConfirm()` method call is blocking, so it may be the reason why it is slower in your case. In this particular case confirms are 15% worse so overall performance difference between transactional and confirmational publishing is relatively small here and needs to be studied more. I would go with more than 1 case, e.g. with 1000 runs or so on some isolated instance (not shared, with constant performance and load across all runs)  and then look on median and cut off all results that are on the edges of normal distribution (if any) to see more reliable picture of what really goes on. I'll take a look at it later when I have time.

**Comment by prolic** [comment]
@pinepain Thank you!

I updated the test-case to use a dataprovider: https://github.com/prolic/php-amqp-test/tree/publish_timing

```
    public function dataProvider()
    {
        return [
            [10],
            [100],
            [1000],
            [10000],
            [100000],
            [1000000]
        ];
    }
```

These are the results from my machine:

```
.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(10)
float(9.2983245849609E-5)

.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(100)
float(0.00036716461181641)

.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(1000)
float(0.0056030750274658)

.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(10000)
float(0.022634029388428)

.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(100000)
float(0.2046070098877)

.string(58) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_default"
int(1000000)
float(8.8480689525604)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(10)
float(0.00034117698669434)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(100)
float(0.0017910003662109)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(1000)
float(0.011436223983765)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(10000)
float(0.13468599319458)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(100000)
float(1.8186860084534)

.string(64) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_transactional"
int(1000000)
float(22.594645023346)

.string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(10)
float(0.00059390068054199)

.string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(100)
float(0.0039258003234863)

.string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(1000)
float(0.038751840591431)

.string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(10000)
float(0.20845293998718)

.string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(100000)
float(1.9945530891418)

string(65) "Prolic\PhpAmqpTest\PublishTimingTest::it_publishes_confirm_select"
int(1000000)
float(18.569562911987)
```

**Comment by pinepain** [comment]
I see the difference. Will play with it and try to find where we have a bottleneck. Thanks!

**Comment by lstrojny** [comment]
@pinepain ping

**Comment by pinepain** [comment]
@lstrojny I get back to this issue multiple time and still have nothing to add to my initial comment above https://github.com/pdezwart/php-amqp/issues/241#issuecomment-232594746: due to how transactions and publish confirms works in rabbitmq and also taking into account that publish confirms implemented in a blocking way, they are both slower then raw publish. The rest performance question should be addressed to rabbitmq internals (sure, taking into account our blocking publish confirms).

I think we can close it for now as there is not too much we can do about original question at this time.

**Comment by lstrojny** [comment]
Thanks so much, @pinepain!

**Comment by prolic** [comment]
Citing https://www.rabbitmq.com/confirms.html:

> Using standard AMQP 0-9-1, the only way to guarantee that a message isn't lost is by using transactions -- make the channel transactional, publish the message, commit. In this case, transactions are unnecessarily heavyweight and decrease throughput by a factor of 250. To remedy this, a confirmation mechanism was introduced. It mimics the consumer acknowledgements mechanism already present in the protocol.

So according to rabbitmq.com confirm select should be faster, not slower.

**Comment by pinepain** [comment]
Hi, thanks for writing. You are absolutely correct, on AMQP level  it is so, though, in php-amqp  we call confirm callback set from `AMQPChannel::setConfirmCallback()` and together with `AMQPChannel::waitForConfirm()` implemented in a blocked manner it adds all that overhead you see in a the benchmark. 

To make it more visible, alter your test case to log confirm callback call, e.g.:

```php
        $channel->setConfirmCallback(
            function (int $deliveryTag, bool $multiple) use ($counter) {
                echo 'calling confirm callback ', $deliveryTag, ' ', ($multiple ? 'multiple' : 'single'), PHP_EOL;
                return ($deliveryTag !== $counter);
            },
            function (int $deliveryTag, bool $multiple, bool $requeue) {
                throw new \RuntimeException('Could not publish all events');
            }
        );
```

In benchmark results we can see that even with all this overhead, publish confirms works a bit faster then transactions.

I would also add that  while transactions and publish confirms could be used to ensure that message(s) was published, these approaches are slightly different in their nature:

 - transactions ensures that all or nothing *published* and/or *ack'ed* messages processed;
 - publish confirms guarantees that single message or all up to specific one are *published*.

**Comment by prolic** [comment]
Thanks @pinepain
