### ISSUE TITLE
why some function is undefined in  AMQPChannel?

### ISSUE THREAD

**Issue by xchz** [pdezwart/php-amqp#242]
hi, i get some problem...
`<?php
var_dump(get_class_methods(AMQPChannel));`
it output:
array(13) {
  [0]=>
  string(11) "__construct"
  [1]=>
  string(11) "isConnected"
  [2]=>
  string(12) "getChannelId"
  [3]=>
  string(15) "setPrefetchSize"
  [4]=>
  string(15) "getPrefetchSize"
  [5]=>
  string(16) "setPrefetchCount"
  [6]=>
  string(16) "getPrefetchCount"
  [7]=>
  string(3) "qos"
  [8]=>
  string(16) "startTransaction"
  [9]=>
  string(17) "commitTransaction"
  [10]=>
  string(19) "rollbackTransaction"
  [11]=>
  string(13) "getConnection"
  [12]=>
  string(12) "basicRecover"
}
if i invoke confirmSelect() , error is 
PHP Fatal error:  Uncaught Error: Call to undefined method AMQPChannel::confirmSelect()

below is my compile steps:
wget https://github.com/alanxz/rabbitmq-c/archive/v0.8.0.tar.gz
tar -zvxf v0.8.0.tar.gz
yum install autoconf automake libtool
autoreconf -i
./configure --prefix=/usr/local/librabbitmq
make && sudo make install

wget https://github.com/pdezwart/php-amqp/archive/v1.7.1.tar.gz
tar -zvxf v1.7.1.tar.gz
/usr/local/php7/bin/phpize
./configure --with-php-config=/usr/local/php7/bin/php-config --with-amqp --with-librabbitmq-dir=/usr/local/librabbitmq
make && sudo make install

then mv modules/amqp.so to php ext directory and and to php.ini file
exec this php -m|grep amqp in commondline can display amqp.
below code is work well:
`    public static function send($message) {

        $connection = new AMQPConnection();

        $connection->setHost('127.0.0.1');

        $connection->setLogin('username');

        $connection->setPassword('password');

        $connection->connect();

        $channel = new AMQPChannel($connection);

        $exchange_name = 'exname';

        $exchange = new AMQPExchange($channel);

        $exchange->setType(AMQP_EX_TYPE_DIRECT);

        $exchange->setName($exchange_name);

        $exchange->declareExchange();

        try{

            $exchange->publish($message, "routing_key");

        }catch(Exception $ex){

            Log::write($message, 'error');

        }

        $connection->disconnect();

    }`
i do not know why AMQPChannel class has no confirmSelect() function.

**Comment by pinepain** [comment]
Hi, I'm not sure that publish confirms available in 1.7.1. Try to build from master branch.

**Comment by xchz** [comment]
hi,thank you for your reply.you are right,confirmSelect() function is not published in 1.7.1. i have build from master branch so i find confirmSelect() function. forgive my poor english ...
