### ISSUE TITLE
Use exception codes correctly

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#243]
F.e. the following exception:

```
Server channel error: 403, message: ACCESS_REFUSED - queue name 'amq.foo' contains reserved prefix 'amq.*'
```

has error code 0 instead of 403. This should be updated.

**Comment by pinepain** [comment]
@prolic 403 is AMQP error code, not PHP exception code. But it may come in handy to propagate that error code to exception. I'll give it a look later this week.

**Comment by prolic** [comment]
this one would be nice for 1.8.0 as well.

**Comment by lstrojny** [comment]
@pinepain yep, reusing the error code would indeed be cute.

**Comment by pinepain** [comment]
I finally get to this. Please, give PR https://github.com/pdezwart/php-amqp/pull/251 a look and test. Thanks!

**Comment by prolic** [comment]
Can be closed now.

Thanks a lot!

1.8.0 release please? :-)
