### ISSUE TITLE
Not compiled as shared together with php sources

### ISSUE THREAD

**Issue by sshilko** [pdezwart/php-amqp#247]
Hi, i'm trying to compile amqp as shared library together with whole php sources (7.0.11)

https://pecl.php.net/get/amqp-1.7.1.tgz
I built php successfuly and building extension by placing it into `ext/amqp`
per http://www.phpinternalsbook.com/build_system/building_extensions.html

and doing`--with-amqp=shared` after `--disable-all` and getting only extensions i need, 
but **amqp is also built statically instead of shared**

i compile `github.com/alanxz/rabbitmq-c` 0.8.0 as shared libraries too correctly
`
cmake \
-DCMAKE_INSTALL_PREFIX=${PHP_LIB_DIR}/rabbitmq-shared \
-DBUILD_EXAMPLES=OFF \
-DBUILD_STATIC_LIBS=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_TOOLS=OFF \
-DENABLE_SSL_SUPPORT=OFF \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_API_DOCS=OFF ..
`

Any ideas why its not built as shared lib, thx.

one thing i found is in `main/php_config.h`

```

/* Whether to build amqp as dynamic module */
/* #undef COMPILE_DL_AMQP */
```

config.log

```
configure:21570: checking for amqp support
configure:21606: result: yes, shared
configure:21615: checking for amqp
configure:21651: result: no
configure:21660: result: yes
```

but config.status has 
`'--with-amqp=shared'`

```
# /usr/local/php7/7.0.11/bin/php -m
[PHP Modules]
amqp
Core
date
filter
hash
json
libxml
mysqli
mysqlnd
pcre
PDO
pdo_mysql
Reflection
session
SPL
standard

[Zend Modules]
```

```

# /usr/local/php7/7.0.11/bin/php --ini
Configuration File (php.ini) Path: /usr/local/php7/7.0.11/etc/cli
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/php7/7.0.11/etc/cli/conf.d
Additional .ini files parsed:      (none)

```

**Comment by pinepain** [comment]
Can you provide steps to reproduce, probably, a list of shell command you run to download, unpack, configure and so on?

**Comment by sshilko** [comment]
[compile_php7.txt](https://github.com/pdezwart/php-amqp/files/518047/compile_php7.txt)

here is my build script

**Comment by sshilko** [comment]
made a complete rebuilt, fresh php sources, freshly fetched  extensions sources.. same - compiled as static

**Comment by pinepain** [comment]
While I'm trying to build in your way, I have few questions:

- Why do you need to build PHP manually?
- Have you tried to install non-core extensions with phpize && ./configure && make install?
- Does packaged PHP 7 with extensions work for you - https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=precise?

**Comment by pinepain** [comment]
Hm. Yeah, it looks it doesn't work, but I can't get why. I've never actually tried to build php with amqp this way and not sure where the problem comes from =(.

**Comment by sshilko** [comment]
1. i use ondrey ppa, works for me, but i need own distribution now for my servers, cant always rely on Sury work.
2.non-core extension (redis) compiles fine as shared when put under ext/redis.
3. yes i use ondrey ppa atm. but switching to own ppa/deb for production servers, only issue is amqp being weird... i will probably work if i compile it with phpize..but for sake of science i want it to be same as others and just compile in 1 go together with sources.

ok i'll have to use phpize then for now

**Comment by sshilko** [comment]
phpize works, but does not recognize custom rabbitmq-c shared libraries https://github.com/pdezwart/php-amqp/issues/248

**Comment by lstrojny** [comment]
closing
