### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#249]
There are quite some differences between v1.7.1 and current master. Escpecially the `AMQPBasicProperties` class. Would you please release a new minor release, so I can rely on a tagged version instead of dev-master?
Thanks a lot.

**Comment by prolic** [comment]
@lstrojny @pinepain 

Ready for 1.8.0 release?

**Comment by lstrojny** [comment]
@prolic I will prepare a beta today

**Comment by lstrojny** [comment]
https://pecl.php.net/package/amqp released

**Comment by prolic** [comment]
Thanks a lot! :+1:
