### ISSUE TITLE
memory leak with pconnect()

### ISSUE THREAD

**Issue by bkw** [pdezwart/php-amqp#25]
Potential sponsor reports memory leaks with pconnect() when used in a loop.
Possibly related: https://bugs.php.net/bug.php?id=63350

**Comment by lstrojny** [comment]
Closing

**Comment by sshilko** [comment]
@pinepain 
just another thanks for a fix, will try again against php-amqplib in production, spending ~50..250ms connecting not fun.

**Comment by pinepain** [comment]
@sshilko if you will play with php-amqp extension, please take a look on persistent connection. It should save you connection time (or use raft extension with php-amqplib). Note, that persistent connection was fixed few weeks ago and not supposed to be stable, so test it and keep eye on it (in general, it should work fine, I just didn't test in under high load).

**Comment by sshilko** [comment]
@pinepain thats exactly what ill try to do.. i use RabbitMQ + PHP  in production for about ~1 year, 
started with php-amqp then switched to pure php "videlalvaro/php-amqplib" and stayed on until now.

* my speed benchmarks (simple publish) actually favored non-extension in spring 2014 
* the persistent connections "closed unexpectedly" :(
* its not straightforward to deploy "php-amqp" i.e.
```
pecl install php-amqp
```
doesnt do the job, same via puppet-pecl

I actually just now read the email about the issue being closed "3 days ago", so will for sure try out
persistent coz connecting to RabbitMQ is at the moment the slowest thing :(

What is the "raft" extension for php-amqplib you mention?

**Comment by pinepain** [comment]
@sshilko, sorry, i mean [raphf](http://pecl.php.net/package/raphf). It was recommended to me on php irc channel as alternative to persistent connections.

As to installing php-amqp via pecl, note that latest version is in beta state, so you have to tell pecl to pick it (see [Unstable alpha/beta packages](http://pear.php.net/manual/en/guide.users.commandline.installing.php#guide.users.commandline.installing.unstable) pecl manual for details).

**Comment by sshilko** [comment]
just another comment to sum it up

* [Michael Wallner](https://github.com/php/pecl-php-raphf) replied RAPHF are non-userland functionality
* installed [amqp-1.6.0beta2](https://github.com/pdezwart/php-amqp/tree/v1.6.0beta2) with [rabbitmq-c v0.5.2](https://github.com/alanxz/rabbitmq-c/tree/v0.5.2) into sandbox environment for me

benchmarks of publishing single message to topic excnahge via AMQP with authorization
```
$time1 = microtime(true);

$cnn = new AMQPConnection($params);
$cnn->pconnect();
//$cnn->connect();
$ch = new AMQPChannel($cnn)
$ex = new AMQPExchange($ch);
$ex->setName('somename');
$ex->setType('topic');
$message_params = array('content_type' => 'application/json', 
                                              'delivery_mode' => 1); //1 == non persistent
//...
$ex->publish($message, $routing_key, 0, $message_params);
/**
* Error (E_WARNING): AMQPConnection::disconnect():
* Attempt to close transient connection while persistent one already established. Abort
*/
//$cnn->disconnect();

$time = microtime(true) - $time1;
```

connect 1.6.0beta2 | pconnect 1.6.0beta2 | [php-amqplib](https://github.com/videlalvaro/php-amqplib)
------------ | ------------- | -------------
 0.0051088333129883 | 0.0019690990447998 | 0.090944051742554
5.61% | 2.16% | 100%

tests done on t1.micro
```
php 5.5.19
t1.micro EC2
Ubuntu 12.04.5 LTS

RabbitMQ server and EC2 instance in same availability region (fast network connection)
```

**looks promising**

**Comment by m6w6** [comment]
Note, RAPHF needs to be implemented explicitly in an extension. It's the perfect fit, though, for extensions using objects having to maintain (persistent) resources that do not have to be exposed to userland.

This is what I wrote to Sergei, when he asked me about RAPHF:

Doxygen API docs are here: http://php.github.io/pecl-php-raphf/php__raphf_8h.html

You can study exemplar code in pecl/http-v2 and pecl/pq, e.g.:
https://github.com/php/pecl-database-pq/blob/master/src/php_pqconn.c#L520-L706
https://github.com/php/pecl-database-pq/blob/master/src%2Fphp_pq_module.c#L59

**Comment by pinepain** [comment]
@m6w6 Thanks for clarifying.
@sshilko sorry for pointing you to the wrong turn.

@sshilko, as to installation, yes, as Ubuntu sux at providing fresh versions of librabbitmq in their repos (I didn't find even any unofficial repo with fresh librabbitmq) you have to install it manually. Maybe someone (or even me when I get tired compile it on every machine) will provide debs for it. I have some plans to do that, but there are a lot of my plate for now.

**About Ubuntu 12.04:** if you didn't have any strict requirements, try to upgrade. As always. But even on 12.04 I had php-amqp with librabbitmq-c installed. Also, check perfomance difference on various ubuntu versions while they have different core libraries versions. 
 
**Performance measurement:** results looks a bit strange, while `pconnect` code is more complicated (in terms of instructions number) then `connect`. In addition, in snippet you provided it looks like you measured whole lifecycle, creating, connecting, publishing, but results labeled as just `pconnect` or `connect` call. Is it expected or just you put the wrong snippet in hurry? And I think it may be useful to run connect in iteration, say, 1000 times (don't forget to close connections for the benches sanity, as RabbitMQ or other broker you used may provide different result when concurrent connections number increased, but that is not for sure that such impact will be significant, at least at this case, but further investigation may be done). 

**About installation:** I use chef for that (not a big fan, but for historical reason on project I worked on). There are [code snippet in issues](https://github.com/pdezwart/php-amqp/issues/131#issuecomment-64878774) for that, but it can be a bit rewritten to utilize latest power of php-amqp extension and librabbitmq (note, in production you'd better to use stable rabbitmq-c, as in original snippet):

```
bash "Install latest stable rabbitmq-c" do
  user 'root'
  cwd '/tmp/'
  code <<-EOH
        rm -rf rabbitmq-c
        git clone -b master git://github.com/alanxz/rabbitmq-c.git
        cd rabbitmq-c
    autoreconf -i && ./configure && make && make install
    cd ..
    rm -rf rabbitmq-c
  EOH
  not_if 'which /usr/local/lib/librabbitmq.so*'
end

php_pear "amqp" do
  version "1.6.0"
  preferred_state "beta"
  action :install
end
```

If you not into chef or just use other provisioner, you can rewrite code for it, I hope idea is clear here.

**Comment by sshilko** [comment]
Looks stable to me so far, deployed with
```
cd /tmp
rm -rf rabbitmq-c
git clone --quiet --depth 1 git://github.com/alanxz/rabbitmq-c.git >/dev/null
cd rabbitmq-c
git checkout --quiet -b v0.5.2
autoreconf -i --warnings=none >/dev/null 2>&1 && ./configure >/dev/null 2>&1 && make --silent > /dev/null && make --silent install >/dev/null
cd /tmp
rm -rf /tmp/rabbitmq-c
```
Pushed to QA for a week, then slowly to production, as expected (see above) saved around 
**10ms** of time average per request 

pure php time per request
![amqp](https://cloud.githubusercontent.com/assets/1147808/6285504/e615d06a-b8fc-11e4-9c12-4f00b3494b23.jpg)
