### ISSUE TITLE
Request for changelog

### ISSUE THREAD

**Issue by pkruithof** [pdezwart/php-amqp#255]
Since 1.8-beta was released, just 45 minutes ago, our Travis builds are failing. We required 1.7 before, but left the stability on beta since it was not stable at that time.

Now this is easily fixed for us to use 1.7 stable, but I was curious about any possible breaking changes in this extension. However I cannot find any documentation for this.

Would greatly appreciate it if a changelog could be added.

**Comment by pinepain** [comment]
What exactly failed on your side? Changelog is available on pecl (https://pecl.php.net/package-changelog.php?package=amqp), you also can list difference between tags - https://github.com/pdezwart/php-amqp/compare/v1.7.1...v1.8.0beta1.

**Comment by pkruithof** [comment]
Ah thanks, I did not know that location. Is the extension released by semver standards? In other words, should I expect no breaking changes from 1.7 to 1.8?

I don't think the error has to do with any breaking changes, as it was simply something like `fatal error: class \AMQPConnection could not be found`. Maybe the extension failed to install on Travis or something. I'll look into that later.

**Comment by lstrojny** [comment]
@pkruithof we indeed try to follow semantic versioning as much as possible so no breaking changes should happen in 1.8.

**Comment by pkruithof** [comment]
Allright, issue can be closed then, thanks for the info!
