### ISSUE TITLE
librabbitmq.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by yeoman-chen** [pdezwart/php-amqp#259]
php -im | grep 'ampq' 

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/amqp.so' - librabbitmq.so.4: cannot open shared object file: No such file or directory in Unknown on line 0

how to solve it ?

**Comment by pinepain** [comment]
Hi! As it written, it hard to provide helpful output. Can you please follow [How to report a problem](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) steps?

**Comment by pinepain** [comment]
I guess we can close this for now, if there will be more details, feels free to submit new issue. Before doing that, check [How to report a problem ](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) link. Thanks! /cc @lstrojny

**Comment by pinepain** [comment]
ping @lstrojny close?

**Comment by lstrojny** [comment]
Yes
