### ISSUE TITLE
Header value is always "true", even when is set to "false"

### ISSUE THREAD

**Issue by madzerling** [pdezwart/php-amqp#261]
When header is set like this:
`
$properties['headers']['test'] = false;
$exchangeObj->publish($content, $queue, AMQP_DURABLE, $properties);
`
Message in RabbitMQ Web admin panel (and in scripts) contains this header set to boolean "true".

**Comment by pinepain** [comment]
Hi! Thanks for reporting.

What php-amqp, PHP and RabbitMQ do you use? Also, minimal complete example to reproduce the issue are highly welcomed (to prevent any misunderstanding).

**Comment by pinepain** [comment]
@madzerling Can you please test whether #264 solves this problem?

**Comment by madzerling** [comment]
I'm using prebuild last avail versions of PHP (7.1) and php-amqp (php-pecl-amqp-1.8.0-0.3.beta2.el7.remi.7.1.x86_64) from REMI centos repo, and Rabbit (RabbitMQ 3.6.6).

To reproduce just connect to rabbit, put message in any query with properties as i mentioned above. Then read this message and check value of this property.
