### ISSUE TITLE
ETA for a stable release supporting PHP 7.1

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#262]
I see that you added support for PHP 7.1 in 1.8-beta2. Do you have an ETA for a stable release supporting PHP 7.1 ?

**Comment by pinepain** [comment]
Hi, existent stable version already has full PHP 7.1 support. Recently added commits are  just about  fixing passing test because of minor change in error message and running extra test against 7.1, but even before that it was known to work with 7.1 RCs.

**Comment by dzuelke** [comment]
Would still be nice to get a stable release tagged sometime; that SSL support would be quite handy :)

**Comment by lstrojny** [comment]
@dzuelke @stof @pinepain targeting 2nd half of January for a new stable release

**Comment by dzuelke** [comment]
Fantastic! Thank you!

**Comment by dzuelke** [comment]
Poke? :)

**Comment by lstrojny** [comment]
@pinepain do you want me to wait for #265?

**Comment by pinepain** [comment]
@lstrojny no, it may take a while and those issues are not critical, we'll include them in a next patch or minor release.

**Comment by lstrojny** [comment]
@pinepain 👍

**Comment by shouze** [comment]
so in this case, maybe guys it's time for a stable release? channel close is a very cool feature that deserves to make a release.

**Comment by lstrojny** [comment]
1.8.0 has been released. Thank's for your patience.
