### ISSUE TITLE
Accept NULL value in headers

### ISSUE THREAD

**Issue by gjedeer** [pdezwart/php-amqp#263]
You even seem to have a [test case](https://github.com/pdezwart/php-amqp/blob/d831c5650237a0abe9721c4386217022ea622c98/tests/amqpexchange_publish_with_properties_ignore_unsupported_header_values.phpt) for assuring that NULL values are not serialized, is it something you plan on implementing or do you have some kind of deeper objections against using NULL?

My use case is the [Celery protocol](http://docs.celeryproject.org/en/latest/internals/protocol.html) which, in version 2, needs quite a few NULL values to work properly.

**Comment by pinepain** [comment]
Hi @gjedeer! In AMQP protocol `NULL` is not supported as a standalone type, the closest data type is `void`, which in meaning is close the same. Does Celery uses it for nulls?

From [AMQP Protocol Specification 4.2.1 Formal Protocol Grammar](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf)

```
field-value         = 't' boolean
                    / 'b' short-short-int
                    / 'B' short-short-uint
                    / 'U' short-int
                    / 'u' short-uint
                    / 'I' long-int
                    / 'i' long-uint
                    / 'L' long-long-int
                    / 'l' long-long-uint
                    / 'f' float
                    / 'd' double
                    / 'D' decimal-value
                    / 's' short-string
                    / 'S' long-string
                    / 'A' field-array
                    / 'T' timestamp
                    / 'F' field-table
                    / 'V'                       ; no field 
```

So now I recall that at the time of refactoring I didn't handle NULL as it was not clear how other libraries/clients handle it. Though, `void` is perfectly fine here. 

Can you confirm that using `void` type for nulls is OK for Celery? I see in a referenced PR you already tried [in this patch](https://github.com/gjedeer/celery-php/issues/78#issuecomment-271099539).

**Comment by gjedeer** [comment]
Thank you for your ultra fast answer! Void worked, although I was not able to test it completely because my patch somehow resulted in an empty array instead of array of two Voids.

It seems so ("None" is Python for "NULL"):
https://github.com/celery/py-amqp/blob/ab395a0a19a52afaec3047e43a7b52b9b31d8313/amqp/serialization.py#L145
https://github.com/celery/py-amqp/blob/ab395a0a19a52afaec3047e43a7b52b9b31d8313/amqp/serialization.py#L398

**Comment by pinepain** [comment]
@gjedeer Can you please test whether #264 solves this problem?

**Comment by gjedeer** [comment]
Yeeeeeeah! It worked, thank you a lot. There are still some failing tests in celery-php but if I discover the problem is related, I'll open another issue.

**Comment by lstrojny** [comment]
Merged
