### ISSUE TITLE
Consumer not removed on read timeout

### ISSUE THREAD

**Issue by DaSteph** [pdezwart/php-amqp#267]
When using amqp.read_timeout and AMQPQueue->consume() is interrupted the consumer resource is not properly cleaned and the targeting RabbitMQ-Server is running in to memory issues:

```
<?php

ini_set('amqp.read_timeout', 3);
$connection = new \AMQPConnection();
$connection->setHost('localhost');
$connection->setLogin('guest');
$connection->setPassword('guest');
$connection->setVhost('local');

$connection->connect();
$channel = new \AMQPChannel($connection);

$queue = new \AMQPQueue($channel);
$queue->setName('testConsume');
$queue->setFlags(AMQP_DURABLE);
$queue->declareQueue();

$handlerCallback = function (\AMQPEnvelope $message, \AMQPQueue $queue) {
    echo "processed message" . PHP_EOL;
    $queue->ack($message->getDeliveryTag());
};

while (1) {
    try {
        $queue->consume($handlerCallback);
    } catch (\AMQPException $e) {
        echo "got error: {$e->getCode()} - {$e->getMessage()}" . PHP_EOL;
    }
}
```

When you let this run and watch the server, you can see, that the number of consumers is increasing until the connection is closed. In our case the connection will not be closed and the number of consumers is increasing all the time causing heavy memory consumption.

**Comment by pinepain** [comment]
Hi @DaSteph, thanks for bringing up this issue!

At this time no consumer canceling done under the hood, so you should probably do it yourself. I would try to do sth like this:

```php
while (1) {
    try {
        $queue->consume($handlerCallback);
    } catch (\AMQPException $e) {
        echo "got error: {$e->getCode()} - {$e->getMessage()}" . PHP_EOL;
        try {
            $queue->cancel();
        } (\AMQPException $e) {
             // TODO: handle canceling exception if you want and need that
        }
    }
}
```

**Comment by DaSteph** [comment]
Dear Bodgan,

thank you very much for this prompt reply. I tested it with my testscript and it looks very promising!
