### ISSUE TITLE
undefined symbol: amqp_ssl_socket_set_verify_peer

### ISSUE THREAD

**Issue by ostin654** [pdezwart/php-amqp#268]
Installed PHP 5.6.30 and now getting WARNING

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - /usr/lib64/php/modules/amqp.so: undefined symbol: amqp_ssl_socket_set_verify_peer in Unknown on line 0

Package php-pecl-amqp-1.8.0-1.el6.remi.5.6.x86_64 installed and the latest version.

**Comment by lstrojny** [comment]
@ostin654  which librabbitmq library (sometimes amqp-c or libamqp) version do you have?

**Comment by ostin654** [comment]
Did not look for it. But after I updated my system (via yum update), everything went fine.
