### ISSUE TITLE
Support dead-lettering headers

### ISSUE THREAD

**Issue by lstrojny** [pdezwart/php-amqp#271]
RabbitMQ will maintain an `x-death` header field where one can see dead lettering metadata (counts, original queues/exchanges, routing keys, etc.). The schema is:

```
reason: string,
queue: string,
time: timestamp,
routing-keys: string[]
```

Right now we are not supporting publishing array and timestamp values so this example of republishing a message from a dead letter queue will not work:

```php
$exchange->publish(
            $envelope->getBody(),
            $envelope->getRoutingKey(),
            AMQP_NOPARAM,
            [
                'content_type' => $envelope->getContentType(),
                'content_encoding' => $envelope->getContentEncoding(),
                'message_id' => $envelope->getMessageId(),
                'user_id' => $envelope->getUserId(),
                'app_id' => $envelope->getAppId(),
                'delivery_mode' => $envelope->getDeliveryMode(),
                'priority' => $envelope->getPriority(),
                'timestamp' => $envelope->getTimeStamp(),
                'expiration' => $envelope->getExpiration(),
                'type' => $envelope->getType(),
                'reply_to' => $envelope->getReplyTo(),
                'headers' => $envelope->getHeaders(),
                'correlation_id' => $envelope->getCorrelationId(),
            ]

);
```
… but instead fail with this error:
```
Message has invalid x-death header (type: table). Resetting header [{<<"0">>,
                                                                     table,
                                                                     [{<<"count">>,
                                                                       long,1},
                                                                      {<<"reason">>,
                                                                       longstr,
                                                                       <<"rejected">>},
                                                                      {<<"queue">>,
                                                                       longstr,
                                                                       <<"QUEUE_NAME">>},
                                                                      {<<"time">>,
                                                                       double,
                                                                       1488404187.0},
                                                                      {<<"exchange">>,
                                                                       longstr,
                                                                       <<"EXCHANGE_NAME">>},
                                                                      {<<"routing-keys">>,
                                                                       table,
                                                                       [{<<"0">>,
                                                                         longstr,
                                                                         <<"ROUTING_KEYS">>}]}]}]

```

### What’s needed
 - Support for arrays
 - Support for timestamp types

Preliminary array support is in 94379069043d13ba812734000fb452a6f62efffb where I encode every PHP array that only consists of numeric indexes as an AMQP array. @pinepain , what do you think about that?

Other than that, timestamp support should be implemented as a value object as discussed in #269.

**Comment by lstrojny** [comment]
@pinepain if you agree with the numeric PHP array to AMQP array strategy, I would first merge just that so that we don’t have merge conflicts for the decimal support case. For decimal support we would hook into `internal_convert_php_to_amqp_field_value()`), same for e.g. for timestamp support.

**Comment by pinepain** [comment]
@lstrojny Hi, thanks for noticing. Yeah, it's clearly a bug/incomplete feature. I gave a look to linked commit (9437906) and it looks good. Please, take a look to my comments there.

As timestamps, how to you plan to store it value (within value object)? Timestamp is `uint64_t`, and `ZEND_LONG_MAX` is `INT64_MAX`, so we potentially may get an overflow. Are we cool to store it as a `double`?

I've also found that we improperly handled `AMQP_FIELD_KIND_U64` case where we read wrong value (we read `i64` instead of `u64`). While it's trivial to fix, here we also potentially faces with the same overflow problem given above. If we OK to store it as double it can be easily done by one of us.

As I'll be adding decimal value object, do you want me to cover timestamp object at that time?

```php
class AMQPTimestamp {
    protected $timestamp;

    /**
     * @param float $timestamp
     */
    public function __construct($timestamp)
    {
        $this->timestamp = $timestamp;
    }
    
    public function getTimestamp() {
        return $this->timestamp;
    }
}
```
not sure about `protected` and namings.

**Comment by lstrojny** [comment]
Very good point on the overflow case. I would say: let's encode as a string internally and be done with it. That way we don't need to care about anything weird.
On handling it: my plan was to work on it over the weekend. I'll start merging the array handling code and then work on timestamp. Maybe you can base decimal support on the merged array handling code to ease merging.

**Comment by lstrojny** [comment]
Another point, as we are starting to go down the value object route: what if we set the following standards:

- each VO has a `__toString()`
- every VO has an interface that we actually rely so that people don't need to inherit from our actual implementations (e.g. In the timestamp case we would rely on `string AMQPTimestampInterface::getTimestamp()` not on the actual concrete implementation. This als makes it easy to bridge third party libraries that already have a higher precision integer

**Comment by pinepain** [comment]
As I wrote above, I'm not fond of idea to keep in extension things that could be implemented in PHP for a maintainability reasons. I saw #257 and think that functionality we discuss are on the edge of v1 and v2. I like the approach in amqplib to force user to explicitly pass type they want to use. It takes out many questions from extension level to userland. In brief - let's keep timestamp/decimal as simple as possible and think about v2. Or even focus on v2 to save our and users time and to prevent doubling efforts. I'll try to bring together thoughts and ideas for v2 and write all that down in #257.

**Comment by lstrojny** [comment]
Fair point, let’s keep it as simple as possible

**Comment by pinepain** [comment]
@lstrojny is it still relevant?

**Comment by lstrojny** [comment]
Can indeed be closed.
