### ISSUE TITLE
cli 已停止工作  window7

### ISSUE THREAD

**Issue by sylarzhou** [pdezwart/php-amqp#277]
问题事件名称:	APPCRASH
  应用程序名:	php.exe
  应用程序版本:	7.1.3.0
  应用程序时间戳:	58c87ee3
  故障模块名称:	php_amqp.dll
  故障模块版本:	7.1.0.0
  故障模块时间戳:	58d523df
  异常代码:	c0000005
  异常偏移:	000000000000ac20
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	caa2
  其他信息 2:	caa2f125106821dd92f2c379391ff584
  其他信息 3:	627e
  其他信息 4:	627efa718b30de860ca6c2846d4e489b

**Comment by pinepain** [comment]
Hi!

Can you please specify following info:
 - platform (x32 or x64);
 - php version and build (`php -v` and `php -i | head -n40`;
 - php-amqp version (`php --ri amqp`) and a way you installed it;
 -  librabbitmq version and a way you installed it.
