### ISSUE TITLE
$queue->setFlags(AMQP_AUTODELETE);  I want to create a defined value like "AMQP_AUTODELETE" ，such as "AMQP_NOTAUTODELETE"

### ISSUE THREAD

**Issue by zx3305** [pdezwart/php-amqp#279]
$queue->setFlags(AMQP_AUTODELETE);  I want to create a defined value like "AMQP_AUTODELETE" ，such as "AMQP_NOTAUTODELETE"

**Comment by pinepain** [comment]
Hi! Queues are created with `auto-delete` flag set to false by default. Note, that if queue has been never used by any consumer, it won't be deleted.

**Comment by pinepain** [comment]
@lstrojny i guess we can close this as not much to do about it.

**Comment by zx3305** [comment]
you are right.
