### ISSUE TITLE
Consume from multiple queues. There is no way to tell what message from what queue came. 

### ISSUE THREAD

**Issue by makasim** [pdezwart/php-amqp#281]
Given the example [amqpqueue_consume_multiple](https://github.com/pdezwart/php-amqp/blob/master/tests/amqpqueue_consume_multiple.phpt) there is no way to tell what was the exact queue the message came from. The [envelop.consumer_tag](https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp.h#L2218) is not taken into account nor [set to message](https://github.com/pdezwart/php-amqp/blob/master/amqp_envelope.c#L61). The second queue argument is always the object the `consume` [method was called on](https://github.com/pdezwart/php-amqp/blob/master/amqp_queue.c#L633). 

Solutions:

1. Add a consumer_tag to the message so we can do assumptions based on it inside the callback.
2. Maintain internally a map consumer_tag -> queue object. And use the correct queue object as the second argument.

The first one is easier to do (If it is ok I can send a PR for it) but the second one is more cleanish.

**Comment by makasim** [comment]
for reference the phpamqplib [supports this behavior](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L985) and the OldSoundRabbitmqBundle provides even a [multiple consumer feature](https://github.com/php-amqplib/RabbitMqBundle#multiple-consumers).

**Comment by pinepain** [comment]
Hi! Thanks for bringing this up. 

Yeah, for some reason `consumer_tag` is missed from `AMQPEnvelope`, just add it.

As to queue to consumer tag, it's a great idea, that second parameter to consumer was known to be broken, so it's a good way to fix that. Will try to take care of it.

**Comment by makasim** [comment]
I'll try to do the first solution ( I am PHP dev but I want to try). The second is way over my head to do myself.

**Comment by pinepain** [comment]
@makasim I've already added consumer tag (see https://github.com/pdezwart/php-amqp/compare/master...pinepain:add-consumer-tag?expand=1), so you can maintain consumer tag to queue on application level. Note that consumer tag is guaranteed to be unique only within channel, so two channels may use the same consumer tag.

**Comment by makasim** [comment]
@pinepain That was way too fast. Thanks! 

Are you going to implement the second part? That's enough what you've done but want to make clear what to expect.

**Comment by pinepain** [comment]
Yeah, working on that, it's a bit tricky as we still need to support PHP 5 which I haven't touch for ages 😄 .

**Comment by pinepain** [comment]
@makasim  Can you please try https://github.com/pdezwart/php-amqp/pull/282 and see whether it is what you mean?

**Comment by makasim** [comment]
@pinepain It works for me. Thanks for your amazing and fast work.
