### ISSUE TITLE
Unit Testing with \AMQP

### ISSUE THREAD

**Issue by J7mbo** [pdezwart/php-amqp#285]
I want to write a simple unit test for an object that uses `\AMQP`. I would like to test how my object responds given exceptions thrown on `\AMQPChannel::__construct()`, however I can't even get to the point where I can test `\AMQPExchange::__construct()` because I can't get past constructing a valid channel - that's because it requires an already connected `AMQPConnection`. Therefore, the whole stack isn't testable.

I can't see what is being called internally by `\AMQPChannel` because, obviously, it's not available in userland, so I can't see how to stub an `\AMQPConnection` correctly to bypass the connection checks.

I'm not trying to test `\AMQP`. I'm trying to *unit test* how my objects respond to using it, and I currently cannot. I'm not able to spin up a new server for an integration test.

Could you please provide any suggestions / ideas on this point? If I can't get past the first hurdle, I cannot have code coverage on the rest and I really want to use the C library as it's significantly superior to the slow PHP implementation.

**Comment by lstrojny** [comment]
Can you give me an example testcase of what you want to do?

**Comment by pinepain** [comment]
You don't have to pass any mocks to constructor, I'd suggest you to mock API methods your app using instead.

**Comment by J7mbo** [comment]
I'm creating a factory for a Queue. I have a Kafka factory and now an AMQP one.

You give the factory a set of credentials and it spits out a Queue object (which is a wrapper around `AMQP` in this instance, with an interface). It throws my own `QueueConnectionException` when it fails, simply because I have to connect before creating the channel.

So the factory interface:

    interface QueueFactory
    {
        /**
         * @throws QueueConnectionException
         */
        public function create(QueueConfiguration $configuration): Queue;
    }

Therefore, `create` will create the `\AMQPConnection`, the `\AMQPChannel`, the `\AMQPExchange` and finally the `\AMQPQueue` - the latter of which I then use to construct my object.

The problem is, firstly, I have to connect in here, in a factory, because creating a channel requires an established connection. Secondly, I can't test creating an exchange and queue because I can never get past the first channel creation part without an integration test.

@lstrojny I don't have a working test case to get past this part yet.

**Comment by makasim** [comment]
I use this package `empi89/php-amqp-stubs` to run unit tests. Of course, the extension should not be installed or disabled. That's easy to do if you run tests in a previously crafted docker container.

**Comment by pinepain** [comment]
@makasim it's very outdated stubs, see #286

**Comment by makasim** [comment]
Yes, it is outdate though it covered my needs. 

#286 looks really good.

**Comment by J7mbo** [comment]
I finally found my way around this... mocking and stubbing everything had to be done in a certain order and.. I needed to isolate the creation of each object in it's own protected factory method (protected so they're not part of the public API, but so PHPUnit could use `getMockForAbstractClass` to access them.

So my test now looks like this with them all stubbed out:

```
        $mockFactory    = $this->getMockBuilder(RabbitMQFactory::class)->setMethods(['createConnection', 'createChannel', 'createExchange', 'createQueue'])->getMockForAbstractClass();
        $mockConnection = $this->getMockBuilder(\AMQPConnection::class)->disableOriginalConstructor()->getMock();
        $mockChannel    = $this->getMockBuilder(\AMQPChannel::class)->disableOriginalConstructor()->getMock();
        $mockExchange   = $this->getMockBuilder(\AMQPExchange::class)->disableOriginalConstructor()->getMock();
        $mockQueue      = $this->getMockBuilder(\AMQPQueue::class)->disableOriginalConstructor()->getMock();

        /** @var RabbitMQFactory|\PHPUnit_Framework_MockObject_MockObject $mockFactory **/
        $mockFactory->expects($this->once())->method('createConnection')->with([])->willReturn($mockConnection);
        $mockFactory->expects($this->once())->method('createChannel')->with($mockConnection)->willReturn($mockChannel);
        $mockFactory->expects($this->once())->method('createExchange')->with($mockChannel)->willReturn($mockExchange);
        $mockFactory->expects($this->once())->method('createQueue')->with($mockChannel)->willReturn($mockQueue);

        $mockFactory->create($this->mockConfig);
```

Having to connect in the factory is still a ballache, though. I'm happy to close this as I just didn't stub it correctly - but is connecting this way a fundamental requirement to how channels work etc?

**Comment by pinepain** [comment]
@J7mbo The problem with connection and channel is that they maintain underlying php resources, which are fully initialized in class constructor: connection resource needs credentials and channel resource needs connection resources, which could be passed only via constructor. While in theory we can do lazy resource initialization upon request, it will heavily contribute to codebase complexity for no good reason. 

Queue and Exchange methods (as well as some Channel) are operating on channel resource and basically they do socket operations with encoding/decoding data according to protocol with the help of C library - librabbitmq and ocking channel and connection object won't help here.

I really feel and share your pita, but unfortunately, there is not much to do about it except mock methods your app gonna use (which in fact is a good thing for **unit** testing).
