### ISSUE TITLE
I want to translate your documents.

### ISSUE THREAD

**Issue by edoger** [pdezwart/php-amqp#287]
I want to translate your documents and put them on my web site. (to chinese language)
Can I do this?

**Comment by lstrojny** [comment]
@edoger what "documents" do you refer to? Documentation? Source code (and documentation) are available under the same license (see https://github.com/pdezwart/php-amqp/blob/master/LICENSE). The provisions defined in that license apply to your case as well.

**Comment by edoger** [comment]
Documentation only! ("/stubs" only!)
I want to translate them into Chinese and put them in my website.

**Comment by pinepain** [comment]
@edoger Thanks for your interest! As Lars said and  AFAIK, from the PHP license point it's ok. To make it rock solid, publish link to this repo and it could be definitely considered as a fair use policy regards, probably, any license (unless it explicitly forbid doing that, which PHP license does not).

**Comment by lstrojny** [comment]
Closing.

**Comment by edoger** [comment]
@lstrojny @pinepain  I already understand. Document translation is ambiguous in many licenses, and this often requires explicit permission from the author.
