### ISSUE TITLE
\AMQPQueue::cancel() causes segfault.

### ISSUE THREAD

**Issue by makasim** [pdezwart/php-amqp#293]
I failed to come up with a small piece of code that reproduces the error but it does segfault in my tests [here](https://github.com/queue-interop/queue-spec/blob/c252543f6c1b0e026aed0561991d076e0b81ee75/src/Amqp/BasicConsumeShouldRemoveConsumerTagOnUnsubscribeSpec.php#L30) and [here](https://github.com/queue-interop/queue-spec/blob/c252543f6c1b0e026aed0561991d076e0b81ee75/src/Amqp/BasicConsumeUntilUnsubscribedSpec.php#L30). If I comment out [this line](https://github.com/php-enqueue/enqueue-dev/blob/69634d72ec7934a60cc4bff92b9df81cfee6d9b1/pkg/amqp-ext/AmqpContext.php#L336) tests obviously fail but there is no segfault. 

That's all I have for now. I'll try to come back with steps to repo.

**Comment by makasim** [comment]
Those tests work for bunny and amqp-lib.

**Comment by pinepain** [comment]
@makasim Hi! Nice catch, thanks! Could you add more details to the issue as per https://github.com/pdezwart/php-amqp#how-to-report-a-problem for better overview, please?

**Comment by makasim** [comment]
That's a copy of [a test](https://github.com/queue-interop/queue-spec/blob/aeedcfd059aef8b317ae803fe6f392a1cdd4560b/src/Amqp/BasicConsumeUntilUnsubscribedSpec.php#L30) where I caught a segfault. 

```php
<?php

/** @var \Enqueue\AmqpExt\AmqpContext context */
        $context = $this->createContext();

        /** @var \Enqueue\AmqpExt\AmqpContext $context */
        $extChannel = $context->getExtChannel();
        $extChannel->qos(0, 3);

        $extQueue = new \AMQPQueue($extChannel);
        $extQueue->setName('foo_basic_consume_until_unsubscribed_spec');
        $extQueue->purge();

        $extQueue = new \AMQPQueue($extChannel);
        $extQueue->setName('bar_basic_consume_until_unsubscribed_spec');
        $extQueue->purge();

        $amqpExchange = new \AMQPExchange($extChannel);
        $amqpExchange->setType(AMQP_EX_TYPE_DIRECT);
        $amqpExchange->setName('');

        $amqpExchange->publish(
            '',
            'foo_basic_consume_until_unsubscribed_spec',
            AMQP_NOPARAM,
            []
        );
        $amqpExchange->publish(
            '',
            'bar_basic_consume_until_unsubscribed_spec',
            AMQP_NOPARAM,
            []
        );

        $extQueue = new \AMQPQueue($extChannel);
        $extQueue->setName('foo_basic_consume_until_unsubscribed_spec');
        $extQueue->consume(null, AMQP_NOPARAM, '');

        $fooConsumerTag = $extQueue->getConsumerTag();

        $extQueue = new \AMQPQueue($extChannel);
        $extQueue->setName('bar_basic_consume_until_unsubscribed_spec');
        $extQueue->consume(null, AMQP_NOPARAM, '');

        $barConsumerTag = $extQueue->getConsumerTag();

        $extConnection = $extChannel->getConnection();

        $originalTimeout = $extConnection->getReadTimeout();
        try {
            $extConnection->setReadTimeout(5);

            $extQueue = new \AMQPQueue($extChannel);
            $extQueue->setName('foo_basic_consume_until_unsubscribed_spec');
            $extQueue->consume(function (\AMQPEnvelope $extEnvelope, \AMQPQueue $q) use ($originalTimeout, $extConnection) {
                $consumeTimeout = $extConnection->getReadTimeout();
                try {
                    $extConnection->setReadTimeout($originalTimeout);

                    var_dump('Message received');

                    return true;
                } finally {
                    $extConnection->setReadTimeout($consumeTimeout);
                }
            }, AMQP_JUST_CONSUME);
        } catch (\AMQPQueueException $e) {
            if ('Consumer timeout exceed' != $e->getMessage()) {
                throw $e;
            }
        } finally {
            $extConnection->setReadTimeout($originalTimeout);
        }

        $extQueue = new \AMQPQueue($extChannel);
        $extQueue->setName('foo_basic_consume_until_unsubscribed_spec');

        // if you uncomment this line you got a seg fault
        // $extQueue->cancel($fooConsumerTag);
```

**Comment by makasim** [comment]
@pinepain do you plan to look into it?

**Comment by pinepain** [comment]
Hi @makasim, thanks for writing. This issue is on my list, though, not at the top. I'm currently heavily busy with my work errands and my pet projects, so taking into account that neither my company nor my project uses this extension, I'm not sure I'll be able to get to this issue anytime soon.

However, I'd really appreciate some sponsorship to work on this task. If anybody interested, feels free to pm me (my email address is available at my github profile page).

**Comment by pinepain** [comment]
@formapro and @makasim offered sponsorship on this issue, which I greatly appreciate! Thanks a lot for supporting opensource software!

**Comment by makasim** [comment]
Wow, The fix has been shipped within an hour. Amazing speed! It would've taken an enormous amount of time to do it ourselves. 

Good job!
