### ISSUE TITLE
Dropping librabbigmq < 0.7.1 support

### ISSUE THREAD

**Issue by pinepain** [pdezwart/php-amqp#301]
Currently Ubuntu 14.04 LTS [has 0.4.1](https://packages.ubuntu.com/trusty/librabbitmq-dev), which we don't support anyway and 16.04 LTS [has 0.7.1](https://packages.ubuntu.com/xenial/librabbitmq-dev).

From php-amqp perspective we highly recommend to have librabbitmq-c > 0.6.0.

I propose to drop everything less then 0.7.1 from support to reduce build matrix and encourage people to use more recent software (bug fixes, security issues, new features, etc.).

I'd suggest to do this drop in next minor release, which I guess could be `1.10.z`.

Are there any objections?

What do you think @lstrojny?

**Comment by lstrojny** [comment]
Sounds good!

**Comment by carlwgeorge** [comment]
@pinepain Would you mind updating the README to match?  It still claims 0.5.2 is the minimum required librabbitmq version.

**Comment by pinepain** [comment]
@carlwgeorge Nice catch, thanks. In advance to updating docs, config.m4 also needs to be updated to reflect that 0.7.2 is the minimal version.

As I'm no longer using this extension actively and that I'm tied up badly by other things, would you (or someone else) mind to provide a PR for this? It shouldn't be that hard: these places needs to be update: https://github.com/pdezwart/php-amqp/blob/master/config.m4#L48-L53 https://github.com/pdezwart/php-amqp/blob/master/config.m4#L124-L130, warning should be removed and version check for error should be altered to check that min version is at least 0.7.2.

**Comment by carlwgeorge** [comment]
Looks like @remicollet beat me too it.  #347

**Comment by remicollet** [comment]
rebased (btw, travis seem stalled)
