### ISSUE TITLE
PHP 7.2 : Unable to load ext

### ISSUE THREAD

**Issue by macintoshplus** [pdezwart/php-amqp#312]
I have open a bug traker here: https://bugs.php.net/bug.php?id=75818

PHP: 7.2
Thread Safe: NTS
Architecture: x64
AMQP Version: 1.9.3

Result: 
```
php -v

Warning: PHP Startup: Unable to load dynamic library 'amqp' (tried: ext\amqp (Th
e specified module could not be found.
), ext\php_amqp.dll (%1 is not a valid Win32 application.
)) in Unknown on line 0
PHP 7.2.1 (cli) (built: Jan  4 2018 04:00:18) ( NTS MSVC15 (Visual C++ 2017) x64
 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.1, Copyright (c) 1999-2017, by Zend Technologies
```

Can you help me ?

**Comment by macintoshplus** [comment]
The pull request from librabbitmq-c for add support OpenSSL 1.1.0
https://github.com/alanxz/rabbitmq-c/pull/471

**Comment by pinepain** [comment]
@macintoshplus thanks for reporting and sorry for late reply.

Unfortunately, I'm not sure this problem could be solved from php-amqp extension side atm as it relies on rabbitmqc so let's wait for the pending fix there.

**Comment by macintoshplus** [comment]
Rebuild the ext is needed ?

**Comment by sshilko** [comment]
I have 7.2.5 running with amqp 1.7.1, all built from sources

**Comment by sshilko** [comment]
php-7.2.5 + amqp-1.7.1 + rabbitmq-c-0.9 working great, all built from sources

**Comment by macintoshplus** [comment]
OK, but I need the DLL version for Windows. I have downloaded the previous version from here: https://windows.php.net/downloads/pecl/snaps/amqp/1.9.3/

If the ext's owner can republish the current version, the version for PHP 7.2 will build automatically for windows.

**Comment by elardvermeulen** [comment]
Any updates on this? Would be nice to be able to use 1.9.3 under windows.

**Comment by lstrojny** [comment]
Closing
