### ISSUE TITLE
 Outdated exception message

### ISSUE THREAD

**Issue by tim-bezhashvyly** [pdezwart/php-amqp#313]
> Notice: Unhandled basic.return method from server received. Use AMQPChannel::setBasicReturnCallback() to process it.

However `AMQPChannel::setBasicReturnCallback()` doe not exist.

**Comment by pinepain** [comment]
Hi, nice catch! Thanks for reporting. Indeed, it should be `AMQPChannel::setReturnCallback`. As it's a trivial fix, do you want to create a PR for this? You can basically do simple `s/setBasicReturnCallback/setReturnCallback/g`.

**Comment by tim-bezhashvyly** [comment]
However I'm afraid `AMQPChannel::setReturnCallback` does not exist either.

**Comment by pinepain** [comment]
It [should](https://github.com/pdezwart/php-amqp/blob/7adc82fadaf9941bc2e06f556ebd1446d29975d9/stubs/AMQPChannel.php#L246) [exist](https://github.com/pdezwart/php-amqp/blob/7adc82fadaf9941bc2e06f556ebd1446d29975d9/amqp_channel.c#L823).

**Comment by tim-bezhashvyly** [comment]
Ah, right. Then this must be a problem of [PHPStorm stub](https://github.com/JetBrains/phpstorm-stubs/blob/master/amqp/amqp.php#L128-L278).

**Comment by pinepain** [comment]
PhpStorm often do not keep it up to date (and current one looks outdated) and as I'm not using php-amqp atm and in general I tend to use local stubs (I used to add them to `require-dev` section in `composer.json`). You may provide PR to their repo (I guess they have a process for that described somewhere in their docs or blog, can't recall right now, but it may be just CONTRIBUTING). 

The culprit in updating PhpStorm stubs may be that current stubs reflect what the latest extension API provides and may not be true for older, and I'm not sure I have definitive answer, it's basically the reason why I use local stubs.

**Comment by tim-bezhashvyly** [comment]
@pinepain Could you please share your local AMQP stub?

**Comment by tim-bezhashvyly** [comment]
@pinepain Ah, those are in `stubs/` dir of this repository. Please disregard my question above. 😊
