### ISSUE TITLE
the extension can not be recognized under PHP 5.3.X since version 1.9.x

### ISSUE THREAD

**Issue by yjqg6666** [pdezwart/php-amqp#316]
The  support for PHP 5.3 has already been dropped? If so, the README.md could be updated.

$php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - /usr/lib64/php/modules/amqp.so: undefined symbol: _php_math_number_format_ex in Unknown on line 0

https://github.com/pdezwart/php-amqp/blob/v1.9.0beta1/amqp_timestamp.c#L61-L71 

The _php_math_number_format_ex API was introduced in PHP 5.4 by commit https://github.com/php/php-src/commit/d2263d482d58180377a3c5e848352dbf0421cb68.

**Comment by pinepain** [comment]
Hi, thanks for bringing this up. AFAIR, PHP versions below 5.6 (all [EOLed](http://php.net/supported-versions.php) versions) as not supported. It may work but it's not guaranteed.

Do you mind to PR min PHP version check? You can use https://github.com/php-v8/php-ref/blob/4129b661b0ff9e60b291d2592de64a7abafbca1b/config.m4#L14-L18 and https://github.com/php-v8/php-ref/blob/4129b661b0ff9e60b291d2592de64a7abafbca1b/php_ref.h#L29-L32 as a reference.

**Comment by yjqg6666** [comment]
Thanks for the reference. I just made a PR.
