### ISSUE TITLE
The readme says that Signal is PHP 5 Only, but that extension says it supports PHP7 as well

### ISSUE THREAD

**Issue by GuillaumeRossolini** [pdezwart/php-amqp#330]
Hi,

At the end of the readme, there is this mention:
> Note, PHP 5 only.

However, in the signal extension's page, they mention support for every PHP 5.3+ branch, and PHP7 too:
https://github.com/rstgroup/php-signal-handler

**Comment by lstrojny** [comment]
Different extension

**Comment by GuillaumeRossolini** [comment]
Of course you're right, but the readme in _this_ project says something about the other project that this other project says isn't true?

They say their project works from PHP 5.3 up to and including 7, while you say their project is PHP 5 only.

**Comment by lstrojny** [comment]
Sorry, I misunderstood you. Let me fix that.
