### ISSUE TITLE
New release for PHP 7.3

### ISSUE THREAD

**Issue by stof** [pdezwart/php-amqp#337]
Please make a new release supporting PHP 7.3

**Comment by hjanuschka** [comment]
`master` has the fix!

`git clone https://github.com/pdezwart/php-amqp.git && cd php-amqp && phpize && ./configure && sudo make install` 🚀

**Comment by stof** [comment]
Sure, but `pecl install` works with released version, which is why I'm asking for a release.

And Heroku will also only install a release in their PHP buildpack, which is why their support for PHP 7.3 does not provide ext-amqp: https://devcenter.heroku.com/changelog-items/1536

**Comment by lstrojny** [comment]
@stof @hjanuschka done
