### ISSUE TITLE
The pre-built DLL not found for PHP 7.2/7.3

### ISSUE THREAD

**Issue by macintoshplus** [pdezwart/php-amqp#339]
The version 1.9.4 has been released in PECL website but the DLL for Windows and for PHP 7.2/7.3 are not found.

The librabbitmq library has been updated ?

https://pecl.php.net/package/amqp/1.9.4/windows

**Comment by lstrojny** [comment]
The build logs seem to be here but I can’t find anything interesting in there: https://windows.php.net/downloads/pecl/releases/amqp/1.9.4/logs/

My knowledge of PHP on Windows is basically non-existent, can anybody help with that?

**Comment by macintoshplus** [comment]
The version 0.9 of the librabbitmq is now into https://windows.php.net/downloads/pecl/deps/
And the build for the PHP 7.2 and 7.3 is now available !

The PECL maintainers gone fix the build.

**Comment by lstrojny** [comment]
Biutiful!
