### ISSUE TITLE
The number of connections for rabbitmq is zero, but AMQPQueue::consume still running.

### ISSUE THREAD

**Issue by gclove** [pdezwart/php-amqp#340]
The number of connections for rabbitmq is zero, but AMQPQueue::consume still running.

```php
// fake code

while (true) {
    AMQPQueue::consume();
}
```

```bash
Version => 1.9.3
Revision => release
Compiled => Jan  7 2019 @ 11:00:46
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.auto_ack => 0 => 0
amqp.cacert => no value => no value
amqp.cert => no value => no value
amqp.channel_max => 256 => 256
amqp.connect_timeout => 0 => 0
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.host => localhost => localhost
amqp.key => no value => no value
amqp.login => guest => guest
amqp.password => guest => guest
amqp.port => 5672 => 5672
amqp.prefetch_count => 3 => 3
amqp.read_timeout => 0 => 0
amqp.timeout => no value => no value
amqp.verify => 1 => 1
amqp.vhost => / => /
amqp.write_timeout => 0 => 0
```

**Comment by ZhukV** [comment]
It's bad issue, but in many cases normal flow with connect to RabbitMQ. Primary problem - client use `select` system function for read from socket. But socket can be dead. If socket dead, you application still run, but messages not received.

For fix this, you can use next solutions:

* Use [heartbeats](https://www.rabbitmq.com/heartbeats.html).
* Use `read_timeout` on connection (if you not receive any messages, application throw exception).
* Use [TCP KeepAlive](https://en.wikipedia.org/wiki/Keepalive)

**Comment by gclove** [comment]
Thanks a lot ~~ @ZhukV
