### ISSUE TITLE
AMQPConnection::isConnected, AMQPChannel::isConnected - maybe need to check the status of connection

### ISSUE THREAD

**Issue by n3b** [pdezwart/php-amqp#35]
if connection was closed - isConnected returns true until any api method called

**Comment by jkobus** [comment]
Method mentioned here is used in [Symfony Messenger](https://github.com/symfony/amqp-messenger/blob/5.4/Transport/Connection.php#L553). Unfortunately, their implementation does not work in my case;
an [AWS RabbitMQ](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-mq-rabbitmq-version-3-8-22/) cluster [has a 350 seconds, fixed, non-changeable idle timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout), and when there's nothing to do for more than 350 seconds it just drops the connection. When an unaware worker tries to dispatch something an exception is thrown. Symfony also does not use blocking calls, so hearbeat is not an option.

I was wondering whether we can think about any solution here @lstrojny, @bkw?
Or maybe I should just try to fix that within the symfony.
