### ISSUE TITLE
amqp 1.9.4 installed but not loaded in php 7.4.

### ISSUE THREAD

**Issue by easternmayurt** [pdezwart/php-amqp#362]
I have installed amqp 1.9.4 with php7.4, it shows in phpinfo(), but when I am trying to use it its not loaded extension_load('amqp'); this return false to me, can anyone help me in this.

**Comment by lexdevelop** [comment]
On PECL latest version does not have build for 7.4 on Windows.
https://pecl.php.net/package/amqp/1.9.4/windows
Can you please create one.
Thanks

**Comment by lstrojny** [comment]
Cannot support this without any further information, closing.
