### ISSUE TITLE
Windows binaries for php 7.4

### ISSUE THREAD

**Issue by diwms** [pdezwart/php-amqp#364]
Hi all :)

Is it possible to somehow get working binaries for windows?

I've investigated a bit logs located here:
https://windows.php.net/downloads/pecl/releases/amqp/1.9.4/logs/

Looks like due to changes in php 7.4
`uint` -> `unsigned`
`ulong` -> `zend_ulong`

version 1.9.4 cannot work together with php 7.4

**Comment by cmb69** [comment]
This has been fixed with commit ca064a4364e7da09e1a6730fca67558c4099d446. Unfortunately, amqp 1.10.0 doesn't build on Windows for different reasons (see PR #368).

**Comment by diwms** [comment]
> This has been fixed with commit [ca064a4](https://github.com/pdezwart/php-amqp/commit/ca064a4364e7da09e1a6730fca67558c4099d446). Unfortunately, amqp 1.10.0 doesn't build on Windows for different reasons (see PR #368).

I'm not sure that this is the reason. 
Because I've to build binaries by myself from the master branch.
And I did it successfully.

**Comment by diwms** [comment]
But I'll be definitely happy if pecl will compile extension for me 👍 
When we can expect this PR to be merged?

**Comment by lstrojny** [comment]
v1.10.1 is released now with the fix for Windows, hope this gives us Windows packages now.

**Comment by AnrDaemon** [comment]
It seems [1.10.2 is compiling now](https://windows.php.net/downloads/pecl/releases/amqp/1.10.2/).

**Comment by lstrojny** [comment]
Wonderful, closing.
