### ISSUE TITLE
AppVeyor: Builds are failing but still show up as successful

### ISSUE THREAD

**Issue by lstrojny** [pdezwart/php-amqp#372]
The 7.2 builds are all failing but still show up as successful on AppVeyor:
 - https://ci.appveyor.com/project/lstrojny/php-amqp/build/job/mklmvo6yxmhanpvh
 - https://ci.appveyor.com/project/lstrojny/php-amqp/build/job/2mk0in8263ftgrhw
 - https://ci.appveyor.com/project/lstrojny/php-amqp/build/job/gnkb6w5bc7qld5yg
 - https://ci.appveyor.com/project/lstrojny/php-amqp/build/job/ghwd63upxr9ed1c6

Let’s let the builds turn red when they can't build.

@cmb69 maybe you can have a look again?

**Comment by lstrojny** [comment]
Was true for the builds before merge already: https://ci.appveyor.com/project/cmb69/php-amqp/build/job/kja0si7gjig90rqa

**Comment by lstrojny** [comment]
Mhh, looking into the artefacts, the .dll file is built. Is it actually succeeding? I am confused, sorry 😕

**Comment by cmb69** [comment]
That is the copied rabbitmq.4.dll, but the php_amqp*.dlls are not build. I'll have a look.

**Comment by cmb69** [comment]
PR #372 should fix this issue. I'll have a look at why the 7.2 builds are failing right away.
