### ISSUE TITLE
Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return value must be of type bool, null returned

### ISSUE THREAD

**Issue by rumours86** [pdezwart/php-amqp#453]
In Connection.php line 459:
                                                                               
  [TypeError]                                                                  
  Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::ack(): Return  
   value must be of type bool, null returned                                   
                                                                               

Exception trace:
  at /app/vendor/symfony/amqp-messenger/Transport/Connection.php:459
 Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection->ack() at /app/vendor/symfony/amqp-messenger/Transport/AmqpReceiver.php:96
 Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpReceiver->ack() at /app/vendor/symfony/amqp-messenger/Transport/AmqpTransport.php:59
 Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransport->ack() at /app/vendor/symfony/messenger/Worker.php:216
 Symfony\Component\Messenger\Worker->ack() at /app/vendor/symfony/messenger/Worker.php:170
 Symfony\Component\Messenger\Worker->handleMessage() at /app/vendor/symfony/messenger/Worker.php:107
 Symfony\Component\Messenger\Worker->run() at /app/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:234
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /app/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /app/bin/console:31

**Comment by lstrojny** [comment]
Already addressed in https://github.com/symfony/symfony/pull/51168
