### ISSUE TITLE
AMQPException: Library error: unexpected protocol state

### ISSUE THREAD

**Issue by basz** [pdezwart/php-amqp#496]
Hi

We are seeing an 'AMQPException: Library error: unexpected protocol state' error. RabbitMQ reports 'client unexpectedly closed TCP connection' in one of our tests.

Apparently when doing `$queue->get()`;

I've since narrowed it down to a difference introduced in 3.10.8 (3.10.7 and before works fine).

Is there way to run amqp with more verbose debug?

https://github.com/basz/HumusAmqp/actions/runs/6246293544/job/16956636702#step:9:25
https://github.com/prolic/HumusAmqp/pull/110#issuecomment-1727294542

**Comment by lstrojny** [comment]
> I've since narrowed it down to a difference introduced in 3.10.8 (3.10.7 and before works fine).

I assume this refers to HumusAmqp? Can you share a link to the diff, maybe that gives some indication?

> Is there way to run amqp with more verbose debug?

Not in the library itself, your best chance is to run RabbitMQ with debug logging enabled.

**Comment by basz** [comment]
I'm working around the issue. 

For reference https://github.com/prolic/HumusAmqp/pull/110#issuecomment-1727545424

**Comment by lstrojny** [comment]
Closing
