### ISSUE TITLE
Can not pass the build on MacOS

### ISSUE THREAD

**Issue by Thenilko** [pdezwart/php-amqp#508]
MacOS Sonoma 14:

- pecl install amqp

Also i tried to download the package and install it manually after i run make -  
Is says: 

running: make
/bin/sh /private/tmp/pear/temp/pear-build-root3q9DPj/amqp-2.1.1/libtool --mode=compile cc -I. -I/private/tmp/pear/temp/amqp -I/private/tmp/pear/temp/pear-build-root3q9DPj/amqp-2.1.1/include -I/private/tmp/pear/temp/pear-build-root3q9DPj/amqp-2.1.1/main -I/private/tmp/pear/temp/amqp -I/opt/homebrew/Cellar/php/8.2.12/include/php -I/opt/homebrew/Cellar/php/8.2.12/include/php/main -I/opt/homebrew/Cellar/php/8.2.12/include/php/TSRM -I/opt/homebrew/Cellar/php/8.2.12/include/php/Zend -I/opt/homebrew/Cellar/php/8.2.12/include/php/ext -I/opt/homebrew/Cellar/php/8.2.12/include/php/ext/date/lib -I/opt/homebrew/Cellar/rabbitmq-c/0.13.0/include  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -DZEND_COMPILE_DL_EXT=1 -c /private/tmp/pear/temp/amqp/amqp.c -o amqp.lo  -MMD -MF amqp.dep -MT amqp.lo
mkdir .libs
 cc -I. -I/private/tmp/pear/temp/amqp -I/private/tmp/pear/temp/pear-build-root3q9DPj/amqp-2.1.1/include -I/private/tmp/pear/temp/pear-build-root3q9DPj/amqp-2.1.1/main -I/private/tmp/pear/temp/amqp -I/opt/homebrew/Cellar/php/8.2.12/include/php -I/opt/homebrew/Cellar/php/8.2.12/include/php/main -I/opt/homebrew/Cellar/php/8.2.12/include/php/TSRM -I/opt/homebrew/Cellar/php/8.2.12/include/php/Zend -I/opt/homebrew/Cellar/php/8.2.12/include/php/ext -I/opt/homebrew/Cellar/php/8.2.12/include/php/ext/date/lib -I/opt/homebrew/Cellar/rabbitmq-c/0.13.0/include -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_COMPILE_DL_EXT=1 -c /private/tmp/pear/temp/amqp/amqp.c -MMD -MF amqp.dep -MT amqp.lo  -fno-common -DPIC -o .libs/amqp.o
git: 'cc' is not a git command. See 'git --help'.

The most similar command is
        gc
make: *** [Makefile:210: amqp.lo] Error 1
ERROR: `make' failed

**Comment by lstrojny** [comment]
Without further context this looks like a very strange error so any further info would be interesting. On the surface it seems like something invokes `git cc`. Do you have any special local configuration that could have an effect like that?

Purely speculative: maybe you have a command not found handler registered in the shell that tries to invoke the command with git?

**Comment by Thenilko** [comment]
Hello @lstrojny , thanks for your time.

After few days of debugging and investigating i end it up with conclusion that is configuration problem on my local machine. I did fresh new install of brew and all the packages and now it works.

"Purely speculative: maybe you have a command not found handler registered in the shell that tries to invoke the command with git?" - probably it was something like this.
