### ISSUE TITLE
PHP AMQP consumer does not respond after a while

### ISSUE THREAD

**Issue by 2233466866** [pdezwart/php-amqp#514]
I got a little problem here with a php amqp consumer, which quits working after a while. Below you can see my silex command. I also tried with heartbeat and keepalive configuration to handle broken network connections, but it does not change. What could be a reason that the consumer does not read the messages from the queue? The script does not quit, it just seems to be sleeping.

[PHP AMQP consumer does not respond after a while](https://stackoverflow.com/questions/36502901/php-amqp-consumer-does-not-respond-after-a-while)

**Comment by lstrojny** [comment]
The example on SO shows you are using phpamqplib, a userland implementation, not this library.

**Comment by 2233466866** [comment]
Thank you very much
