### ISSUE TITLE
amqp windows dll for php 8.2

### ISSUE THREAD

**Issue by luimen6** [pdezwart/php-amqp#522]
Where can I find the dll for php 8.2?
https://pecl.php.net/package/amqp
I can only find the dll for 1.11.0. This version is not compatible with php 8.2

**Comment by lstrojny** [comment]
pecl.php.net does not provide Windows builds at the moment, see https://windows.php.net/ for more information on what is happening.

Checkout https://github.com/php-amqp/php-amqp/discussions/477 on where to find pre-built binaries or go directly to https://phpext.phptools.online/extension/networking/amqp-178 to download pre-built binaries.
