### ISSUE TITLE
Impossible to install on windows (Unable to load dynamic library 'amqp')

### ISSUE THREAD

**Issue by FlorianGuiot** [pdezwart/php-amqp#581]
Hi, I'm having a problem installing amqp.
Note that I tried with PHP versions 8.2, 8.2.22 and 8.3.10 (and with their versions of AMQP) in TS and NTS.

1. I have downloaded the extension for PHP 8.2, TS x64 on [](https://pecl.php.net/package/amqp/2.1.2/windows) 
2. I dragged the php_amqp.dll file into the php8.2.0\ext folder, where all my other extensions are located. 
3. I dragged the rabbitmq.4.ddl and rabbitmq.4.pdb files into the php8.2.0 folder.
4. I added ‘extension=amqp’ to php.ini
5. My php system and user environment variables point to C:\wamp64\bin\php\php8.2.0

When I type 'php -m' I get : 

`Warning: PHP Startup: Unable to load dynamic library 'amqp' (tried: c:/wamp64/bin/php/php8.2.0/ext/amqp (Le module spécifié est introuvable), c:/wamp64/bin/php/php8.2.0/ext/php_amqp.dll (Le module spécifié est introuvable)) in Unknown on line 0`

(Le module spécifié est introuvable = The specified module cannot be found)

I have the impression that this is a common problem but I don't understand where it comes from. Can someone please help me?

**Comment by ukr357** [comment]
Hi, same for me. I am running PHP 8.2.22 (TS x64) on Windows 11. I downloaded the appropriated extension (php_amqp-2.1.2-8.2-ts-vs16-x64.zip) and did the same steps as described above. My Path variable includes the PHP 8.2.22 root folder. This setup worked well for php_amqp-1.11.0-8.1-ts-vs16-x64.zip. But now, I get the error:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'amqp' (tried: ext\amqp (The specified module could not be found), ext\php_amqp
.dll (The specified module could not be found)) in Unknown on line 0
```
Please help!

**Comment by ukr357** [comment]
I just found a comment in the Discussion on Third-party Windows builds and downloaded the dlls from https://phpext.phptools.online/extension/amqp-178. This worked right away :-)

**Comment by FlorianGuiot** [comment]
it works! thanks a lot
