### ISSUE TITLE
Missing `php_amqp.pdb` file in windows release package extension

### ISSUE THREAD

**Issue by stackpan** [pdezwart/php-amqp#583]
Hi, I’m having trouble installing the AMQP extension. I’ve downloaded the extension from https://pecl.php.net/package/amqp, but I couldn’t find the `.pdb` file in the extracted package.

According to the installation instructions, the following files should be included: `php_amqp.dll`, `php_amqp.pdb`, `rabbitmq.4.dll`, and `rabbitmq.4.pdb`. However, the `php_amqp.pdb` file is missing from the extension package.

When I try to install the extension by placing only `php_amqp.dll` in the `ext` folder, I encounter the following error when checking the list of installed extensions in PHP:
```bash
> php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'amqp' (tried: ext\amqp (The specified module could not be found), ext\php_amqp.dll (The specified module could not be found)) in Unknown on line 0
```

Could you please help me with this?

Additional information:
OS: Windows 10
PHP: 8.3.11 VS16 x64 TS
Amqp package: 2.1.2 for Windows - for PHP 8.3 x64 TS

**Comment by YepYuYu** [comment]
I'm having the same problem.

**Comment by stackpan** [comment]
Nevermind. I solved the issue from this: https://github.com/php-amqp/php-amqp/issues/581
