### ISSUE TITLE
Implement RabbitMQ tutorials

### ISSUE THREAD

**Issue by gjuric** [pdezwart/php-amqp#62]
Since the documentation is practically non-existent, it would be nice if somebody would implement [tutorials from the RabbitMQ site](http://www.rabbitmq.com/getstarted.html).

Maybe this would be less time consuming then trying to update the whole documentation and it would certainly be of much help to the newcomers.

Repo with tutorials for other languages and implementations is located at [rabbitmq/rabbitmq-tutorials](https://github.com/rabbitmq/rabbitmq-tutorials)

**Comment by A-j-K** [comment]
#174  Please give feedback there on that PR. Thank you.

**Comment by bweston92** [comment]
Updates? I seen there was a PR but still open.

**Comment by dedalozzo** [comment]
The example are here:

https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/php-amqp

**Comment by pinepain** [comment]
@lstrojny as there are already RabbitMQ tuttorials and less likely we have any further plan to do anything on this issue, let's close it.

**Comment by dedalozzo** [comment]
I strongly suggest to link them in the README.

**Comment by lstrojny** [comment]
@dedalozzo care to open a PR for it?

Closing this for now
