### ISSUE TITLE
Problems with non existing exchanges.

### ISSUE THREAD

**Issue by odolbeau** [pdezwart/php-amqp#78]
1. When you published a message in an unknown exchange, then a message in a known exchange, the second one is not published (except with a new Channel).
2. If a new exchange is used, a Fatal Error occured when trying to get the message (even with a new Channel).

You can find a full example [in this gist](https://gist.github.com/odolbeau/7750376).

**Comment by knodir** [comment]
Hello,

I am facing this issue in rabbitmq of the OpenStack, as described [here](https://ask.openstack.org/en/question/81500/returning-exception-exchangedeclare-404-not_found-no-exchange/). Is there known solutions?

Thanks!

**Comment by tuwid** [comment]
Hi,
this issue happens when the queue has auto_delete true, please set that to false and you should get rid of this error by making the queues persistent.
