### ISSUE TITLE
QOS

### ISSUE THREAD

**Issue by dovidkopel** [pdezwart/php-amqp#87]
I did manage to install the library now. However, I am receiving this error:

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/amqp.so' - /usr/lib/php5/20100525/amqp.so: undefined symbol: amqp_basic_qos in Unknown on line 0`

Then I get a fatal error saying that the Class 'AMQPConnection' is not found.

**Comment by pinepain** [comment]
Just to note, sometimes after juggling with librabbitmq version you'll have to run `phpize --clean` before rebuilding php-amqp extension.
