### ISSUE TITLE
Release buffer on exception

### ISSUE THREAD

**Issue by kinncj** [pdezwart/php-amqp#99]
https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L596

In this line, if the buffer is not ok, ```amqp_maybe_release_buffers``` (https://github.com/alanxz/rabbitmq-c/blob/b852f846c46a3bb9451f99844edfbea41f3289f1/librabbitmq/amqp_connection.c#L402) will not release the buffer.

The behaviour is ok if you don't catch the exception.. but once you catch the exception, the php process still stuck due to the buffer...

Should call ```amqp_release_buffers``` directly and release the buffer instead of ```amqp_maybe_release_buffers``` ?

**Comment by lstrojny** [comment]
Closing
